Repository istio/ztunnel, pull requests merged in 2022-12, with the labels that each got.

#218 clean fetch_certificate
  src/identity/manager.rs
Labels: size/M

#161 separate threads for admin and proxy
  src/admin/mod.rs
  src/app.rs
  src/main.rs
  src/proxy/mod.rs
  src/proxy/socks5.rs
Labels: size/L

#229 Fix cache_rx.changed() blocking
  benches/throughput.rs
  src/app.rs
  src/identity/manager.rs
  src/main.rs
  src/test_helpers/app.rs
  tests/proxy.rs
Labels: size/S

#219 Use more standard casing in outputs
  examples/localhost.yaml
  src/proxy/outbound.rs
  src/workload.rs
Labels: size/M

#234 Use local address as a fallback for SO_ORIGINAL_DST.
  src/socket.rs
Labels: size/XS

#237 Simplify the relay error capture and debug formatter
  src/proxy/inbound.rs
Labels: size/XS

#226 Add benchmark for connections and metrics
  benches/throughput.rs
  src/lib.rs
Labels: size/M

#236 Exit immediately when double ctrl+c
  src/signal.rs
Labels: size/XS

#238 add more data to config_dump API
  src/admin/mod.rs
  src/config.rs
  src/version.rs
Labels: size/M

#239 Integrate Codespace
  .devcontainer/devcontainer.json
  docker/remote-env/Dockerfile
Labels: size/M

#240 add a test to expect failures with configured addresses
  tests/proxy.rs
Labels: size/S

#211 Handle the hbone copy error gracefully
  src/proxy/inbound.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
Labels: size/S

#235 Use socket2 crate instead of reimplementing socket options.
  Cargo.lock
  Cargo.toml
  src/socket.rs
Labels: size/L

#244 metrics: implement connections metric with full set of labels
  Cargo.lock
  Cargo.toml
  benches/throughput.rs
  src/app.rs
  src/identity/manager.rs
  src/metrics/mod.rs
  src/metrics/traffic.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/test_helpers/app.rs
  tests/proxy.rs
Labels: size/XL

#254 xds: allow multiple types
  src/workload.rs
  src/xds/client.rs
  src/xds/types.rs
Labels: size/L

#262 Do some cleanup after https://github.com/istio/ztunnel/pull/252
  src/workload.rs
Labels: size/M

#265 Clean up logging a bit
  Cargo.toml
  src/admin/mod.rs
  src/hyper_util.rs
  src/identity/manager.rs
  src/main.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/socket.rs
  src/telemetry.rs
  src/test_helpers/app.rs
  src/workload.rs
  src/xds/client.rs
Labels: size/XL

#256 xds: pass metadata, including NODE_NAME
  proto/xds.proto
  src/xds/client.rs
Labels: size/S

#255 Reduce code duplication in XDS handler
  src/xds/client.rs
Labels: size/M

#266 Verify control plane SAN
  src/app.rs
  src/config.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/outbound.rs
  src/test_helpers/ca.rs
  src/tls/boring.rs
  src/tls/mod.rs
  src/xds/client.rs
Labels: size/L

#258 Add test for request to a VIP
  examples/localhost.yaml
  src/admin/mod.rs
  src/config.rs
  src/test_helpers/mod.rs
  src/workload.rs
  tests/proxy.rs
Labels: size/L

#267 minor readme update for fips disablement
  LOCAL.md
Labels: size/XS

#263 Abstract tokio runtime shut down check
  src/proxy/inbound_passthrough.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/proxy/util.rs
Labels: size/M

#271 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#274 Logging: fix build error when console is enabled
  src/telemetry.rs
Labels: size/XS

#275 Add check for features building
  Makefile.core.mk
Labels: size/XS

#269 logging: cleanup and expand scope
  Cargo.lock
  Cargo.toml
  src/admin/mod.rs
  src/app.rs
  src/telemetry.rs
Labels: size/L

#272 fix two e2e test flakes
  src/app.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/mod.rs
  tests/proxy.rs
Labels: size/M

#277 Automator: update common-files@master in istio/ztunnel@master
  .gitattributes
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#278 Automator: update common-files@master in istio/ztunnel@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#243 Admin api improvements
  benches/throughput.rs
  src/admin/mod.rs
  src/app.rs
  src/config.rs
  src/lib.rs
  src/readiness/mod.rs
  src/readiness/server.rs
  src/test_helpers/app.rs
  src/test_helpers/mod.rs
  src/workload.rs
  src/xds/client.rs
  tests/proxy.rs
Labels: size/L

#284 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#286 Automator: update common-files@master in istio/ztunnel@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#268 waypoints: disable consumer waypoints
  src/proxy/outbound.rs
Labels: size/M

#283 change waypoint proxy port to 15008
  src/proxy/outbound.rs
Labels: size/XS

#289 readiness: fix never getting ready
  src/app.rs
  src/test_helpers/app.rs
Labels: size/XS

#290 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#291 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#292 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#279 e2e tests: cleanup IP usage
  src/test_helpers/app.rs
  src/test_helpers/mod.rs
  tests/proxy.rs
Labels: size/M

#296 add AMBIENT_TYPE to connection metadata
  src/xds/client.rs
Labels: size/XS

#299 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#300 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
