Repository istio/ztunnel, pull requests merged in 2022-11, with the labels that each got.

#41 local docs: add step for getting a token
  LOCAL.md
Labels: size/S

#42 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#43 Update LOCAL.md
  LOCAL.md
Labels: size/XS

#45 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#51 Make linter pass 1.65.0 rust version
  build.rs
  src/identity/auth.rs
  src/xds/client.rs
  src/xds/mod.rs
Labels: size/XS

#50 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#54 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#53 Fixes to work in real k8s cluster
  src/main.rs
  src/proxy/outbound.rs
Labels: size/XS

#52 Initial support for on demand xds
  Cargo.toml
  src/admin/mod.rs
  src/config.rs
  src/proxy/inbound.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/workload.rs
  src/xds/client.rs
  src/xds/mod.rs
Labels: size/XL

#55 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#56 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#58 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#59 Fix calls to pods on the same node
  src/proxy/outbound.rs
Labels: size/XS

#61 Support IPv4 and IPv6 compatibility for function to_canonical_ip
  src/proxy/mod.rs
Labels: size/S

#60 use the lib definition for both LOCALHOST and UNSPECIFIED
  src/workload.rs
Labels: size/S

#57 xds: break out huge tokio::select statement
  src/xds/client.rs
Labels: size/L

#102 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#100 Add some starter unit tests for `build_request`
  src/proxy/outbound.rs
  src/workload.rs
Labels: size/L

#66 outbound: pick random upstream instead of first
  Cargo.lock
  Cargo.toml
  src/workload.rs
Labels: size/XS

#62 Implement basic graceful drain/exit of proxy
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/config.rs
  src/lib.rs
  src/main.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/signal.rs
  src/telemetry.rs
  tests/helpers.rs
  tests/proxy.rs
Labels: size/L

#103 Implement `baggage` header for outbound calls
  src/proxy/outbound.rs
  src/workload.rs
Labels: size/M

#63 use UNSPECIFIED for socketAddr and reduce a parameter for the Builder::new
  src/admin/mod.rs
  src/app.rs
  src/config.rs
Labels: size/S

#105 Fix and test local XDS client
  src/workload.rs
Labels: size/S

#106 reduce copypaste for local dev
  LOCAL.md
  scripts/local.sh
Labels: size/M

#108 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#104 improve set_gateway_ip
  src/workload.rs
Labels: size/S

#113 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#117 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#109 performance: set TCP_NODELAY and increase copy buffer
  src/proxy/inbound.rs
  src/proxy/mod.rs
Labels: size/S

#122 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#116 remove unnecessary clone for workload when building request
  src/proxy/outbound.rs
Labels: size/S

#124 Use env to generate node id for xds client
  src/xds/client.rs
Labels: size/S

#65 Convert find_upstream to rust style && refactor build_request
  src/proxy/outbound.rs
  src/workload.rs
Labels: size/L

#107 add shutdown trigger from the admin server
  src/admin/mod.rs
  src/app.rs
  src/signal.rs
  tests/proxy.rs
Labels: size/M

#112 Implement to configure the Tokio worker threads number
  src/config.rs
  src/main.rs
Labels: size/S, ok-to-test

#123 Fix workload removal from VIP
  src/workload.rs
Labels: size/L

#121 Add version subcommand to report version info
  Cargo.lock
  Cargo.toml
  build.rs
  src/lib.rs
  src/main.rs
  src/version.rs
Labels: size/L

#119 outbound: add one more test case for VIPs
  src/proxy/outbound.rs
Labels: size/M

#129 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#130 trim dependencies a bit
  Cargo.lock
  Cargo.toml
  build.rs
Labels: size/L

#126 Fix inbound connect failure panic
  src/proxy/inbound.rs
Labels: size/M

#125 Fix build request panic
  src/proxy/outbound.rs
Labels: size/M

#132 rename gateway_ip to gateway_address
  src/proxy/outbound.rs
  src/workload.rs
Labels: size/S

#137 `make update-common` and fix `make lint`
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS

#134 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#111 Add Socks5 support for easier local debugging
  Cargo.lock
  Cargo.toml
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
Labels: size/L

#135 outbound: improve tests and error handling
  src/proxy/mod.rs
  src/proxy/outbound.rs
Labels: size/L

#133 chore: fix copyright banner
  Makefile.core.mk
  build.rs
  common/Makefile.common.mk
  common/scripts/fix_copyright_banner.sh
  scripts/local.sh
  src/admin/mod.rs
  src/app.rs
  src/config.rs
  src/identity/auth.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/identity/mod.rs
  src/lib.rs
  src/main.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/signal.rs
  src/telemetry.rs
  src/tls/boring.rs
  src/tls/mod.rs
  src/version.rs
  src/workload.rs
  src/xds/client.rs
  src/xds/mod.rs
  tests/helpers.rs
  tests/proxy.rs
Labels: size/L

#131 rewrite bi stream data copy with native tokio::io::copy_bidirectional
  src/proxy/outbound.rs
Labels: size/S

#147 Make waypoint_addresses vec
  proto/workload.proto
  src/proxy/outbound.rs
  src/workload.rs
Labels: size/M

#138 Integ test: improve coverage and remove sleep
  src/admin/mod.rs
  src/app.rs
  src/config.rs
  src/main.rs
  src/proxy/inbound.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  tests/proxy.rs
Labels: size/L

#118 verify certs/sans on outbound
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/tls/boring.rs
Labels: size/L

#145 Add a script to set tproxy capture
  scripts/tproxy.sh
Labels: size/M

#141 outbound: implement in memory fast path, bypassing full HBONE connection
  LOCAL.md
  examples/localhost.yaml
  src/proxy/inbound.rs
  src/proxy/outbound.rs
Labels: size/L

#151 Initial full request end to end tests
  examples/localhost.yaml
  src/app.rs
  src/config.rs
  src/identity/caclient.rs
  src/lib.rs
  src/proxy/inbound.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/test_helpers/app.rs
  src/test_helpers/echo.rs
  src/test_helpers/helpers.rs
  src/test_helpers/mod.rs
  src/tls/boring.rs
  src/tls/mod.rs
  src/workload.rs
  src/xds/client.rs
  tests/proxy.rs
Labels: size/L

#142 chore: fix lint issues
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  src/proxy/socks5.rs
  src/socket.rs
  src/test_helpers/app.rs
  src/test_helpers/echo.rs
  src/test_helpers/mod.rs
Labels: size/M

#146 Update ssl connector setting
  src/tls/boring.rs
Labels: size/XS

#46 Cert cache + refresh logic
  src/app.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/inbound.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/tls/boring.rs
Labels: size/L, ok-to-test

#155 tests: add e2e hbone test
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/inbound.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/test_helpers/app.rs
  src/tls/boring.rs
  src/tls/ca-key.pem
  src/tls/cert-chain.pem
  src/tls/gen-certs.sh
  src/tls/key.pem
  src/tls/mod.rs
  src/tls/root-cert.pem
  tests/proxy.rs
Labels: size/L

#162 Prevent panic when uri is invalid
  src/proxy/inbound.rs
Labels: size/S

#157 Add real readiness logic
  src/admin/mod.rs
  src/app.rs
  src/test_helpers/app.rs
  src/workload.rs
  tests/proxy.rs
Labels: size/L

#164 readiness: add duration and fix release builds
  src/admin/mod.rs
  src/telemetry.rs
Labels: size/S

#163 optimized the workload store struct
  src/workload.rs
Labels: size/M

#172 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#167 check SAN of CA response
  src/identity/caclient.rs
  src/identity/mod.rs
  src/tls/boring.rs
Labels: size/M

#173 Explicitly fallback on orig_dst lookup failure
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/socket.rs
  src/tls/boring.rs
  tests/proxy.rs
Labels: size/M

#168 Add initial throughput and latency benchmark
  Cargo.lock
  Cargo.toml
  Makefile.core.mk
  benches/README.md
  benches/throughput.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/test_helpers/app.rs
  src/test_helpers/echo.rs
  src/test_helpers/mod.rs
  src/test_helpers/tcp.rs
Labels: size/XL

#170 zero copy between two socket for passthrough mode
  Cargo.lock
  Cargo.toml
  src/proxy/inbound.rs
  src/proxy/outbound.rs
Labels: size/S

#176 bi copy support cross platform
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/socket.rs
Labels: size/M

#177 simplify result conversion by map
  src/socket.rs
Labels: size/S

#181 Remove unused dependencies.
  Cargo.lock
  Cargo.toml
Labels: size/XS

#179 Use zero-copy in passthrough mode.
  src/proxy/inbound_passthrough.rs
Labels: size/S

#180 Simplify processing of environment variables.
  src/config.rs
Labels: size/S

#182 Change gateway to upstream workload waypoint address
  src/proxy/outbound.rs
Labels: size/XS

#178 Change the worker thread name for tracing easily
  src/main.rs
Labels: size/XS, ok-to-test

#175 Refactor benchmark a bit
  benches/throughput.rs
  src/test_helpers/echo.rs
  src/test_helpers/mod.rs
  src/test_helpers/tcp.rs
  tests/proxy.rs
Labels: size/L

#186 Remove option to run without TLS
  src/config.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
Labels: size/L

#187 xds: use TLS (port 15012) to control plane
  src/config.rs
  src/xds/client.rs
Labels: size/M

#189 Fix the worker threads environment name typo
  src/config.rs
Labels: size/XS, ok-to-test

#202 Fix integration with tokio-console.
  src/telemetry.rs
Labels: size/XS

#198 Add option to configure address of the control plane.
  src/config.rs
Labels: size/S

#200 Move the argv handling out of async context
  src/main.rs
Labels: size/S, ok-to-test

#192 minior improve serve_connect
  src/proxy/inbound.rs
Labels: size/M

#193 update byte_to_ip return value type
  src/workload.rs
Labels: size/M

#196 Process local XDS config at startup.
  src/app.rs
  src/workload.rs
Labels: size/M

#197 Add option to use the builtin mock as a fake CA.
  src/app.rs
  src/config.rs
Labels: size/S

#206 use const strings for env config variables
  src/config.rs
Labels: size/S, ok-to-test

#207 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#159 admin: add metrics endpoint
  Cargo.lock
  Cargo.toml
  src/admin/mod.rs
  src/app.rs
  src/lib.rs
  src/monitoring.rs
  src/test_helpers/app.rs
  src/version.rs
  src/workload.rs
  src/xds/client.rs
  src/xds/mod.rs
  src/xds/monitoring.rs
Labels: size/L

#188 Simplified caching logic, changed expiration handling to use SystemTi…
  src/identity/manager.rs
  src/tls/boring.rs
Labels: size/L

#210 follow up review comments
  src/monitoring.rs
  src/xds/client.rs
  src/xds/monitoring.rs
Labels: size/XS

#171 inbound graceful shutdown
  src/proxy/inbound.rs
  src/proxy/mod.rs
  tests/proxy.rs
Labels: size/M

#190 Xds readiness
  README.md
  src/app.rs
  src/workload.rs
  src/xds/client.rs
Labels: size/M

#213 Add e2e test for inbound draining
  src/proxy/inbound.rs
  tests/proxy.rs
Labels: size/M

#215 unit test caclient directly
  src/identity/caclient.rs
  src/identity/mod.rs
  src/tls/boring.rs
Labels: size/L

#216 metrics: refactor, expand, and test
  src/app.rs
  src/lib.rs
  src/metrics/meta.rs
  src/metrics/mod.rs
  src/metrics/traffic.rs
  src/metrics/xds.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/test_helpers/app.rs
  src/workload.rs
  src/xds/client.rs
  src/xds/mod.rs
  src/xds/monitoring.rs
  tests/proxy.rs
Labels: size/L

#212 Improve config parsing and documentation for local runs
  Cargo.lock
  Cargo.toml
  LOCAL.md
  src/config.rs
  src/main.rs
  src/proxy/outbound.rs
  src/test_helpers/mod.rs
  tests/proxy.rs
Labels: size/L

#222 Revert "unit test caclient directly (#215)" causing stack overflow
  src/identity/caclient.rs
  src/identity/mod.rs
  src/tls/boring.rs
Labels: size/L

#224 Re-introduces CA tests
  Cargo.lock
  Cargo.toml
  build.rs
  src/config.rs
  src/hyper_util.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/identity/mod.rs
  src/lib.rs
  src/proxy/inbound.rs
  src/test_helpers/ca.rs
  src/test_helpers/fake-jwt
  src/test_helpers/mod.rs
  src/tls/boring.rs
Labels: size/L
