Repository istio/ztunnel, pull requests merged in 2022-10, with the labels that each got.

#31 Add doc for local testing
  LOCAL.md
Labels: size/M

#32 Create `presubmit` test for CI and setup build container
  Makefile.core.mk
  Makefile.overrides.mk
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/report_build_info.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/S

#30 tls: use real certificates
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile.core.mk
  examples/localhost.yaml
  src/config.rs
  src/identity/auth.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/identity/mod.rs
  src/main.rs
  src/proxy/inbound.rs
  src/proxy/mod.rs
  src/proxy/outbound.rs
  src/socket.rs
  src/tls/boring.rs
  src/workload.rs
  src/xds/client.rs
Labels: size/L

#33 Automator: update common-files@master in istio/ztunnel@master
  .gitattributes
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#34 Add initial script for publishing release binaries
  Makefile.core.mk
  scripts/release.sh
Labels: size/M

#37 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#38 Add stubs for non linux original destination funcs
  src/socket.rs
Labels: size/S, ok-to-test

#36 Audit clone usages
  src/workload.rs
Labels: size/L, ok-to-test
