Repository istio/ztunnel, pull requests merged in 2023-09, with the labels that each got.

#676 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#677 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#678 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#679 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#680 fix : make ambient work with intermidiary certs
  src/tls/boring.rs
  src/tls/ca-chain.pem
  src/tls/cert-chain.pem
  src/tls/cert.pem
  src/tls/gen-certs.sh
  src/tls/intermediary-cert.pem
  src/tls/intermediary-key.pem
  src/tls/istiod-cert.pem
  src/tls/istiod-key.pem
Labels: size/L, ok-to-test

#683 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#684 remove use of new_socket_addr() in dns server tests
  src/dns/server.rs
Labels: size/M

#685 better SocketAddr creation
  src/dns/server.rs
Labels: size/XS

#688 [release-1.19] Make ztunnel accept intermediary certs
  src/tls/boring.rs
  src/tls/ca-chain.pem
  src/tls/cert-chain.pem
  src/tls/cert.pem
  src/tls/gen-certs.sh
  src/tls/intermediary-cert.pem
  src/tls/intermediary-key.pem
  src/tls/istiod-cert.pem
  src/tls/istiod-key.pem
Labels: size/L

#682 Add port for hbone single TLS
  build.rs
  proto/workload.proto
  src/admin.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
Labels: size/M

#690 xds: pass ISTIO_METAJSON_* env vars in node matadata
  src/xds/client.rs
Labels: size/L

#692 Add oneway tls port to waypoint
  proto/workload.proto
  src/admin.rs
  src/proxy/outbound.rs
  src/state/workload.rs
Labels: size/S

#693 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#694 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none
