Repository istio/ztunnel, pull requests merged in 2023-06, with the labels that each got.

#538 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#542 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#543 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#544 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#546 Add cluster_id to AuthSource Token to support multicluster authentication
  src/config.rs
  src/identity/auth.rs
  src/test_helpers/ca.rs
Labels: size/S

#547 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#545 Refactoring WorkloadStore and ServiceStore
  examples/localhost.yaml
  fuzz/fuzz_targets/protobuf.rs
  src/admin.rs
  src/app.rs
  src/cert_fetcher.rs
  src/lib.rs
  src/metrics/traffic.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/rbac.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/test_helpers/xds.rs
  src/tls/boring.rs
  src/workload.rs
  src/xds.rs
  src/xds/client.rs
  tests/namespaced.rs
Labels: size/XXL

#549 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#548 Add a help command for the ztunnel cli
  src/main.rs
Labels: size/S, ok-to-test

#551 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#552 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#553 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#562 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#565 Add tests for change_log_level
  src/admin.rs
Labels: size/L

#567 Revert "Add tests for change_log_level"
  src/admin.rs
Labels: size/L

#566 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#536 Initial DNS proxy implementation
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/admin.rs
  src/config.rs
  src/lib.rs
  src/proxy.rs
  src/proxy/dns.rs
  src/proxy/dns/forwarder.rs
  src/proxy/dns/name_util.rs
  src/proxy/dns/proxy.rs
  src/proxy/dns/resolver.rs
  src/proxy/outbound.rs
  src/state.rs
  src/test_helpers.rs
  src/test_helpers/dns.rs
  src/test_helpers/helpers.rs
  src/test_helpers/linux.rs
Labels: size/XXL

#568 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#570 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#571 Abstract repetitive code for building test workload into it's own function
  src/test_helpers.rs
Labels: size/M

#573 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#559 Add RBAC to benches
  benches/throughput.rs
  src/test_helpers.rs
  src/test_helpers/xds.rs
Labels: size/L, ok-to-test

#561 bench script
  scripts/benchtest.sh
Labels: size/S, ok-to-test

#574 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#575 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#576 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#578 Fail if using DNS with on-demand
  src/config.rs
  src/proxy.rs
Labels: size/M
