Repository istio/ztunnel, pull requests merged in 2023-05, with the labels that each got.

#508 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#509 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#511 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#512 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#514 Add CODEOWNERs
  CODEOWNERS
Labels: size/XS

#516 [CNCF graduation] Add security tab for Istio repos
  .github/SECURITY.md
Labels: size/XS

#518 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#520 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#523 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#486 Ambient xds evolution
  build.rs
  examples/localhost.yaml
  fuzz/fuzz_targets/protobuf.rs
  proto/authorization.proto
  proto/workload.proto
  src/admin.rs
  src/config.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/rbac.rs
  src/test_helpers.rs
  src/test_helpers/components.rs
  src/test_helpers/xds.rs
  src/tls/boring.rs
  src/workload.rs
  src/xds/client.rs
  src/xds/types.rs
  tests/namespaced.rs
Labels: size/XXL, ok-to-test

#524 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#527 Better function signatures for cert verifiers
  src/tls/boring.rs
Labels: size/S

#522 Remove global TERMINATION_GRACE_PERIOD
  src/admin.rs
  src/app.rs
  src/config.rs
  tests/direct.rs
Labels: size/M

#513 Improve certificate prefetching
  src/workload.rs
Labels: size/S

#528 Fix build and test on macos
  Cargo.toml
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
  tests/README.md
  tests/namespaced.rs
Labels: size/XXL

#530 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#531 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/S, auto-merge, release-notes-none

#529 Update `Workload` primary xds key to UID
  examples/localhost.yaml
  proto/workload.proto
  src/admin.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/workload.rs
  src/xds/client.rs
  tests/namespaced.rs
Labels: size/XL

#534 [release-1.18] Manual update-common and update client/h2-timer# commits to latest
  Cargo.lock
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  fuzz/Cargo.lock
Labels: size/XS

#526 config dump: cleanup json representation a bit
  src/admin.rs
  src/workload.rs
Labels: size/M, release-notes-none

#535 Less noisy workload deletion
  src/workload.rs
Labels: size/S
