Repository istio/ztunnel, pull requests merged in 2023-01, with the labels that each got.

#301 xds/client: fix node metadata keys
  src/xds/client.rs
Labels: size/XS, ok-to-test

#303 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#305 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#297 implement L4 AuthorizationPolicy
  Cargo.lock
  Cargo.toml
  benches/throughput.rs
  build.rs
  examples/localhost.yaml
  proto/google/protobuf/empty.proto
  proto/networkpolicy.proto
  proto/workload.proto
  src/admin/mod.rs
  src/identity/manager.rs
  src/identity/mod.rs
  src/lib.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/rbac.rs
  src/telemetry.rs
  src/test_helpers/mod.rs
  src/tls/boring.rs
  src/workload.rs
  src/xds/client.rs
  src/xds/types.rs
Labels: size/XXL

#308 bump thiserror to 1.0.38
  Cargo.lock
  Cargo.toml
Labels: size/S

#306 POD_NAME should be changed to NAME
  src/xds/client.rs
Labels: size/XS

#309 build: bump tls-listener from 0.5.1 to 0.6.0
  Cargo.lock
  Cargo.toml
Labels: size/XS

#302 fuzz: introduce initial fuzz targets
  fuzz/.gitignore
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  fuzz/fuzz_targets/protobuf.rs
Labels: size/XXL, auto-merge

#316 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#294 parse proxy config
  proto/README.md
  proto/google/protobuf/wrappers.proto
  src/config.rs
  src/identity/auth.rs
  src/test_helpers/mesh_config.yaml
  src/xds/client.rs
Labels: size/L

#315 refactor modules to remove mod.rs files
  src/admin.rs
  src/identity.rs
  src/metrics.rs
  src/proxy.rs
  src/readiness.rs
  src/test_helpers.rs
  src/tls.rs
  src/xds.rs
Labels: size/XS, ok-to-test

#317 Add bytes sent and received metrics
  src/config.rs
  src/metrics.rs
  src/metrics/traffic.rs
  src/metrics/xds.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/socket.rs
  src/test_helpers.rs
  tests/proxy.rs
Labels: size/L

#318 config: correct admin and status ports
  src/admin.rs
  src/config.rs
Labels: size/XS, ok-to-test

#313 Bump prometheus client to 0.19.0
  Cargo.lock
  Cargo.toml
  benches/throughput.rs
  src/admin.rs
  src/identity/manager.rs
  src/metrics/meta.rs
  src/metrics/traffic.rs
  src/metrics/xds.rs
Labels: size/L

#325 Make caclient not require `mut`
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/M

#327 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#324 Handle upstream proto renames
  build.rs
  proto/authorization.proto
  src/rbac.rs
  src/workload.rs
  src/xds/client.rs
  src/xds/types.rs
Labels: size/L

#323 log version we are running as
  src/main.rs
Labels: size/XS

#304 Implement inbound passthrough hairpin
  benches/throughput.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/rbac.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/tcp.rs
  src/tls/boring.rs
  src/workload.rs
  tests/proxy.rs
Labels: size/XL

#330 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#331 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#332 Bump rust to 1.66.1
  Cargo.lock
Labels: size/M

#264 support original source proxy
  src/config.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/socket.rs
Labels: size/L

#298 prefetch certs on workload discovery
  src/app.rs
  src/workload.rs
Labels: size/M

#335 check node before prefetching
  src/workload.rs
Labels: size/S

#328 Remove warnings when building on non-linux env
  src/socket.rs
Labels: size/M

#336 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#337 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#339 Replace wrong IPs with constants
  benches/throughput.rs
Labels: size/S

#338 Add bytes received and sent to hbone connection
  src/proxy.rs
  src/proxy/outbound.rs
Labels: size/S

#340 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#341 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#319 tests: use network namespaces
  Cargo.lock
  Cargo.toml
  Makefile.core.mk
  benches/throughput.rs
  scripts/node-redirect.sh
  scripts/ztunnel-redirect.sh
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/components.rs
  src/test_helpers/helpers.rs
  src/test_helpers/netns.rs
  src/test_helpers/tcp.rs
  src/workload.rs
  tests/README.md
  tests/direct.rs
  tests/namespaced.rs
Labels: size/XXL, ok-to-test

#329 Fix regression with setting empty environment variable
  src/config.rs
Labels: size/M

#333 orig src: cleanups from initial impl
  Cargo.lock
  Cargo.toml
  scripts/node-redirect.sh
  scripts/ztunnel-redirect.sh
  src/app.rs
  src/config.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/test_helpers/components.rs
  src/test_helpers/netns.rs
  tests/namespaced.rs
Labels: size/XL

#343 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#344 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#280 (feat) Add `cargo deny` to check for CVEs & allowed licenses
  Makefile.core.mk
  deny.toml
Labels: size/M, ok-to-test

#345 admin: split stats into its own port
  ARCHITECTURE.md
  benches/throughput.rs
  src/admin.rs
  src/app.rs
  src/config.rs
  src/hyper_util.rs
  src/lib.rs
  src/main.rs
  src/readiness/server.rs
  src/stats.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/components.rs
  tests/direct.rs
Labels: size/XL

#350 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#352 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#348 Fix hairpin when client and waypoint are remote
  src/proxy.rs
  src/proxy/inbound_passthrough.rs
  tests/namespaced.rs
Labels: size/M

#354 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#356 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#346 fuzz: fix build and test in CI
  Makefile.core.mk
  fuzz/Cargo.lock
  fuzz/fuzz_targets/protobuf.rs
Labels: size/L

#349 Add tests to calls to sensitive ztunnel ports
  src/config.rs
  src/proxy.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/test_helpers/app.rs
  src/test_helpers/components.rs
  src/test_helpers/netns.rs
  tests/namespaced.rs
Labels: size/L

#358 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#355 fix dockerfile for remote-env lint issues
  docker/remote-env/Dockerfile
Labels: size/XS, ok-to-test

#362 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#361 Run cargo fmt for 1.67.0
  build.rs
  src/admin.rs
  src/app.rs
  src/identity/manager.rs
  src/proxy/inbound.rs
  src/rbac.rs
  src/telemetry.rs
  src/test_helpers/netns.rs
  src/workload.rs
  tests/direct.rs
Labels: size/M

#366 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#364 waypoints: lookup identity instead of assuming same
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/tls/boring.rs
  src/workload.rs
Labels: size/M

#261 Issue #227: Adds mock XDS server for unit tests.
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/test_helpers.rs
  src/test_helpers/xds.rs
  src/xds/client.rs
Labels: size/L
