Repository istio/ztunnel, pull requests merged in 2023-11, with the labels that each got.

#721 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#723 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#724 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#728 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#734 Update 1.20 common-files
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  src/admin.rs
  src/dns/server.rs
  src/identity/manager.rs
  src/test_helpers/tcp.rs
Labels: size/S

#738 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb-native.yaml
  common/scripts/metallb.yaml
Labels: size/XXL, auto-merge, release-notes-none
