Repository istio/ztunnel, pull requests merged in 2023-12, with the labels that each got.

#740 base64 encode secrets in config_dump
  src/admin.rs
Labels: size/L

#743 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#744 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#745 Automator: update common-files@release-1.20 in istio/ztunnel@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#746 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#563 Add proxy meta cluster id config to ztunnel
  src/config.rs
Labels: size/XS

#748 Fix typos in doc/comment by https://github.com/crate-ci/typos
  Cargo.toml
  proto/authorization.proto
  proto/workload.proto
  src/proxy/socks5.rs
  src/test_helpers/app.rs
  src/xds/client.rs
  tests/namespaced.rs
Labels: size/S, ok-to-test

#749 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#750 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#753 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#751 xds: fix removals
  src/xds.rs
  src/xds/client.rs
Labels: size/S, release-notes-none

#754 make sure that authorization policies XDS is never in on-demand mode
  src/test_helpers/xds.rs
  src/xds.rs
  src/xds/client.rs
Labels: size/L

#755 bugfix: update proxy state before xds state
  src/test_helpers/xds.rs
  src/xds/client.rs
Labels: size/L

#756 wait for caches of not on-demand resources to warm, and block proxy on that
  src/app.rs
  src/state.rs
  src/test_helpers/xds.rs
  src/xds/client.rs
Labels: size/L

#757 Make proxy cache updates consistent
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/xds.rs
  src/xds/client.rs
Labels: size/L
