Repository istio/ztunnel, pull requests merged in 2023-08, with the labels that each got.

#629 Cleanup and test Service metrics
  benches/throughput.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/service.rs
  src/test_helpers/linux.rs
  tests/namespaced.rs
Labels: size/L

#632 xds: refactor client to be type-agnostic
  src/state.rs
  src/test_helpers/xds.rs
  src/xds/client.rs
Labels: size/L, release-notes-none

#633 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#637 [release-1.19] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#630 metrics: report Service from inbound side as well
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/service.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#640 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#645 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#627 enhance wl xds logging
  src/xds.rs
Labels: size/XS

#646 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#647 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#650 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#651 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#652 Pretty print config
  src/admin.rs
Labels: size/S

#620 Async ssl config provider for xDS and CA connections
  src/app.rs
  src/config.rs
  src/hyper_util.rs
  src/identity.rs
  src/identity/auth.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/inbound.rs
  src/state.rs
  src/test_helpers/ca.rs
  src/test_helpers/xds.rs
  src/tls/boring.rs
  src/xds.rs
  src/xds/client.rs
Labels: size/L, auto-merge

#656 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#657 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#655 Update Hyper to 1.0.0-rc4
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/hyper_util.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/test_helpers/ca.rs
  src/test_helpers/tcp.rs
  src/test_helpers/xds.rs
  src/tls/boring.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#662 Add tcp keepalives for xDS client connection
  src/tls/boring.rs
Labels: size/XS

#669 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#670 Remove "useless vec!"s
  build.rs
  src/dns/server.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/pool.rs
  src/rbac.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers/netns.rs
  src/xds/client.rs
Labels: size/M

#663 Optimize XDS errors
  src/xds.rs
  src/xds/client.rs
Labels: size/M, release-notes-none

#631 HBONE connections benches
  benches/throughput.rs
  examples/localhost.yaml
  src/test_helpers/app.rs
  tests/direct.rs
Labels: size/L

#671 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#674 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
