Repository istio/ztunnel, pull requests merged in 2023-03, with the labels that each got.

#427 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#421 Support forgetting Identities
  src/identity.rs
  src/identity/manager.rs
Labels: size/L

#428 Automator: update common-files@master in istio/ztunnel@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#430 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#429 Fix handling of requests about the same Identity but different priority
  src/identity/manager.rs
Labels: size/L

#431 Set the baggage cluster ID from the env
  src/config.rs
  src/proxy/outbound.rs
Labels: size/S

#432 Clean up use of SecretManager
  src/app.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/test_helpers/app.rs
  src/workload.rs
  tests/namespaced.rs
Labels: size/L

#437 Support trust domain
  src/test_helpers.rs
  src/workload.rs
Labels: size/S

#439 Get and use Cluster ID from the WDS
  proto/workload.proto
  src/metrics/traffic.rs
  src/test_helpers.rs
  src/workload.rs
Labels: size/S

#444 Parse baggage on destination ztunnel
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/util.rs
Labels: size/M

#445 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#446 Cleanup and update deps
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
Labels: size/XL

#443 getting correct xds_root_cert info for config with the same logic of FindRootCAForXDS in Istio
  src/config.rs
Labels: size/M

#442 Support setting: DISABLE_IMPERSONATED_IDENTITY
  src/config.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/inbound_passthrough.rs
  src/test_helpers/ca.rs
  src/workload.rs
Labels: size/M

#454 Remove redudent match in workload::byte_to_ip()
  src/workload.rs
Labels: size/XS

#456 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#434 Include secrets in /config_dump
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/admin.rs
  src/app.rs
  src/identity.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/time.rs
  src/tls/boring.rs
  src/tls/ca-key.pem
  src/tls/cert-chain.pem
  src/tls/gen-certs.sh
  src/tls/key.pem
  src/tls/root-cert.pem
Labels: size/L

#458 fix lint
  src/proxy/outbound.rs
  src/test_helpers/app.rs
Labels: size/XS

#457 update copyright
  src/xds/types.rs
Labels: size/S

#459 bump dependencies
  Cargo.lock
Labels: size/L

#460 Support multiline baggage header parsing
  fuzz/fuzz_targets/baggage.rs
  src/baggage.rs
  src/proxy/inbound.rs
Labels: size/M

#462 skip serializing bytes content of root certs
  src/config.rs
Labels: size/XS

#463 assume https for xds and ca
  src/config.rs
Labels: size/M

#467 socks5: change message from self-call to unknown dst
  src/proxy/outbound.rs
Labels: size/XS

#464 add state to secrets output
  src/admin.rs
  src/identity/manager.rs
Labels: size/M

#465 Rename proxy mode "Sidecar" to "Serverless"
  src/config.rs
  src/identity/manager.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/workload.rs
Labels: size/S

#449 enhance the xds and ca certificates finding
  src/config.rs
Labels: size/S

#470 disable san check on ca response for dedicated proxy
  src/identity/caclient.rs
  src/test_helpers/ca.rs
Labels: size/S

#471 Add tests for Initializing and Unavailable cert states in config_dump
  src/admin.rs
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/M

#473 XDS_ROOT_CA env variable not taken
  src/config.rs
Labels: size/XS

#472 Tweak config_dump format for certs
  src/admin.rs
  src/identity/manager.rs
Labels: size/M

#478 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#477 Remove obsolete comment
  src/admin.rs
Labels: size/XS

#482 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: size/L, auto-merge, release-notes-none

#476 Disable console log color
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/telemetry.rs
Labels: size/XS

#483 Bump dependencies
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/socket.rs
Labels: size/XL

#475 Add simple dashboard to ztunnel admin
  src/admin.rs
  src/assets/dashboard.html
Labels: size/L
