Repository istio/ztunnel, pull requests merged in 2023-07, with the labels that each got.

#579 Small cleanup to service store remove logic
  src/state/service.rs
Labels: size/M

#580 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#583 Remove unused vip field
  proto/workload.proto
  src/admin.rs
  src/proxy/inbound.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/xds.rs
Labels: size/L

#584 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#586 Various cleanup to ProxyState
  src/proxy/dns.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/policy.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/xds.rs
Labels: size/XL

#585 DNS proxy should handle IPv4-in-IPv6 like TCP proxy does.
  src/proxy/dns.rs
Labels: size/M

#588 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#590 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#589 DNS support for headless services
  src/proxy/dns.rs
Labels: size/L

#591 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#593 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#595 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#596 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#556 implement service entry SANs matching
  src/identity/caclient.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/state.rs
  src/state/service.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/tls/boring.rs
  tests/namespaced.rs
Labels: size/M

#597 Adding metrics for DNS.
  src/metrics.rs
  src/metrics/dns.rs
  src/metrics/traffic.rs
  src/proxy.rs
  src/proxy/dns.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
  tests/direct.rs
Labels: size/XL

#602 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#603 Fix for DNS system forwarder
  src/proxy/dns.rs
  src/proxy/dns/forwarder.rs
  src/proxy/dns/proxy.rs
  src/proxy/dns/resolver.rs
Labels: size/L

#605 Allow configuring cluster domain
  src/app.rs
  src/config.rs
  src/dns/server.rs
Labels: size/S

#607 Automator: update common-files@release-1.18 in istio/ztunnel@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#609 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#610 update dependencies
  Cargo.lock
  src/socket.rs
Labels: size/L

#611 Waypoint workload IP cannot match tcp workload
  src/test_helpers.rs
Labels: size/XS

#601 add tests for service subjectAltNames
  examples/localhost.yaml
  src/state/workload.rs
Labels: size/XS

#613 add a logs message when starting dns server
  src/dns/server.rs
Labels: size/XS

#614 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#615 Set NODELAY when accepting H2 connections
  src/hyper_util.rs
Labels: size/XS

#617 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#619 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#612 Implement on-demand hostname for Workloads
  proto/workload.proto
  src/admin.rs
  src/config.rs
  src/dns/server.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/policy.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/test_helpers/xds.rs
  src/xds.rs
  tests/direct.rs
Labels: size/XL

#622 Update ondemand dns metric name
  src/config.rs
  src/proxy/metrics.rs
  src/state.rs
  src/test_helpers.rs
  tests/direct.rs
Labels: size/M

#624 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/L, auto-merge, release-notes-none

#626 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/S, auto-merge, release-notes-none

#625 Set label destination_service_name and destination_service_namespace to L4 metrics
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/state.rs
Labels: size/S

#628 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
