Repository istio/ztunnel, pull requests merged in 2023-02, with the labels that each got.

#370 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#372 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#376 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#377 remove obsolete redirect logic
  scripts/ztunnel-redirect.sh
Labels: size/XS

#378 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#373 move more strings to constants
  src/identity/manager.rs
Labels: size/XS

#371 More TCP metrics support
  Cargo.lock
  Cargo.toml
  benches/throughput.rs
  fuzz/Cargo.lock
  src/config.rs
  src/metrics.rs
  src/metrics/traffic.rs
  src/metrics/xds.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/socket.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/netns.rs
  src/test_helpers/tcp.rs
  src/xds/client.rs
  tests/direct.rs
  tests/namespaced.rs
Labels: size/XL

#383 Fix markdown lint
  ARCHITECTURE.md
  tests/README.md
Labels: size/XS

#382 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#380 Issue #9: Handled some expects()/unwraps()
  src/proxy.rs
  src/proxy/outbound.rs
  src/tls/boring.rs
Labels: size/S

#386 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#384 Few fixes for build on non-linux os
  src/socket.rs
Labels: size/S

#389 Clean up identity mock code
  benches/throughput.rs
  src/app.rs
  src/identity.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/outbound.rs
  src/test_helpers/app.rs
  src/test_helpers/components.rs
  tests/direct.rs
Labels: size/L

#390 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#395 Publish arm64 binary
  scripts/release.sh
Labels: size/XS

#396 Fix arm64 build
  scripts/release.sh
Labels: size/XS

#398 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#391 Implement prioritized certificate fetching
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/identity.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/lib.rs
  src/time.rs
  src/tls.rs
  src/tls/boring.rs
Labels: size/XL

#397 Fix version metric to report Istio version
  src/metrics/meta.rs
  src/version.rs
Labels: size/S

#403 slight cleanup in fips enabled tests
  src/tls/boring.rs
Labels: size/S

#405 slight cleanup in fips enabled tests
  src/tls/boring.rs
Labels: size/XS

#409 Always print backtrace on `cargo test`
  Makefile.core.mk
Labels: size/XS

#411 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#412 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#414 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#401 check expected grpc error
  src/metrics/xds.rs
  src/xds/client.rs
Labels: size/S

#408 Add istio meta prefix metadata to proxy metadata
  .gitignore
  src/config.rs
Labels: size/M

#415 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#406 Clean up error handling in Secret Manager
  src/identity/manager.rs
Labels: size/M

#417 Add XDS keepalives, like we have in Go
  src/tls/boring.rs
Labels: size/XS

#418 auditing clone usage
  src/config.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/rbac.rs
  src/readiness.rs
  src/tls/boring.rs
  src/workload.rs
  src/xds/client.rs
Labels: size/M

#420 add backoff for gRPC errors
  src/xds/client.rs
Labels: size/S

#422 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none
