Repository istio/ztunnel, pull requests merged in 2023-04, with the labels that each got.

#492 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#493 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#451 deps: update to hyper 1.0.0
  Cargo.lock
  Cargo.toml
  benches/README.md
  fuzz/Cargo.lock
  src/admin.rs
  src/app.rs
  src/hyper_util.rs
  src/identity/caclient.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/readiness/server.rs
  src/stats.rs
  src/test_helpers/app.rs
  src/test_helpers/ca.rs
  src/test_helpers/tcp.rs
  src/test_helpers/xds.rs
  src/tls/boring.rs
  src/xds/client.rs
  tests/direct.rs
  tests/namespaced.rs
Labels: size/XXL

#494 Manual update of common-files
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS

#496 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#499 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#498 Validate SAN trust domain during mTLS
  src/proxy/inbound.rs
  src/test_helpers/components.rs
  src/tls/boring.rs
  tests/namespaced.rs
Labels: size/L

#495 Fix rbac rule matching
  src/rbac.rs
Labels: size/L

#502 reduce number of buffers used when handling hbone traffic
  src/proxy.rs
Labels: size/XS

#505 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#506 [release-1.18] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#507 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#293 Implement connection pooling
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/proxy.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/tls/boring.rs
  tests/namespaced.rs
Labels: size/XL, lifecycle/automatically-closed

#501 sample changes to proto
  examples/localhost.yaml
  proto/authorization.proto
  src/rbac.rs
Labels: size/M
