Repository istio/ztunnel, pull requests merged in 2024-12, with the labels that each got.

#1371 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1372 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1373 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1374 Reformat with Rust 1.83
  src/drain.rs
  src/proxy/inbound.rs
  src/rbac.rs
  src/state/workload.rs
  src/telemetry.rs
  src/xds.rs
Labels: size/M, release-notes-none, cherrypick/release-1.24

#1376 Automator: update common-files@release-1.22 in istio/ztunnel@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1378 debugging: add some extra debug logs to introspect HBONE requests
  src/proxy/h2/server.rs
  src/proxy/inbound.rs
Labels: size/S, release-notes-none, cherrypick/release-1.24

#1377 Add default TCP keepalives
  src/config.rs
  src/dns/server.rs
  src/inpod/config.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxyfactory.rs
  src/test_helpers/dns.rs
Labels: size/L, cherrypick/release-1.24

#1379 [release-1.24] debugging: add some extra debug logs to introspect HBONE requests
  src/proxy/h2/server.rs
  src/proxy/inbound.rs
Labels: size/S, release-notes-none

#1381 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1380 [release-1.24] Add default TCP keepalives
  src/config.rs
  src/dns/server.rs
  src/inpod/config.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxyfactory.rs
  src/test_helpers/dns.rs
Labels: size/L, release-notes-none

#1382 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1383 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1384 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1385 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1388 add PROXY_WORKLOAD_INFO env var to inpodserver
  Development.md
  examples/inpodserver.rs
Labels: size/M, ok-to-test

#1389 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1390 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1391 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1387 Use rustup llvm tools
  scripts/test-with-coverage.sh
Labels: size/XS

#1393 Actually use rustup llvm tools
  scripts/test-with-coverage.sh
Labels: size/XS

#1394 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1395 [release-1.23] xds: gracefully handle stream termination without error
  src/xds/client.rs
Labels: size/S, release-notes-none

#1397 Bump dependencies
  Cargo.lock
  Cargo.toml
  deny.toml
  examples/inpodserver.rs
  fuzz/Cargo.lock
  src/inpod/protocol.rs
  src/proxy/outbound.rs
  src/state.rs
  src/tls/control.rs
  src/tls/lib.rs
  src/xds.rs
  tests/namespaced.rs
Labels: size/XXL

#1396 Expose configuration parsing errors to user
  src/config.rs
Labels: size/M, release-notes-none, cherrypick/release-1.24

#1401 [release-1.24] Expose configuration parsing errors to user
  src/config.rs
Labels: size/M, release-notes-none

#1398 1.24: minimal dep updates
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
Labels: size/L, release-notes-none

#1400 enable dependabot to auto update deps
  .github/dependabot.yml
Labels: size/S, release-notes-none

#1403 Tidy `DelWorkload` handling in a pre-snapshot context
  src/inpod/statemanager.rs
Labels: size/M

#1405 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
