Repository istio/ztunnel, pull requests merged in 2024-09, with the labels that each got.

#1291 h2: drop spammy ping/pong errors
  src/proxy/h2.rs
  src/proxy/h2/server.rs
Labels: size/S, release-notes-none, cherrypick/release-1.23

#1293 h2: drop spammy ping/pong errors (#1291)
  src/proxy/h2.rs
  src/proxy/h2/server.rs
Labels: size/S, release-notes-none

#1290 Remove deadcode in waypoint_svc_ip_address
  src/state/workload.rs
Labels: size/S, release-notes-none

#1295 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1297 Silence new warnings with rust 1.80
  build.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#1294 inbound: unconditionally log errors
  src/proxy/h2/server.rs
  src/proxy/inbound.rs
  src/proxy/metrics.rs
Labels: size/L, release-notes-none

#1299 refactor: rename ClientCertProvider to clarify it is for control plane usage
  src/identity/caclient.rs
  src/tls/control.rs
  src/tls/lib.rs
  src/xds/client.rs
Labels: size/S, release-notes-none

#1300 Makefile: fix bad `fmt` args
  Makefile.core.mk
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#1301 release.sh: support building alternative TLS providers
  README.md
  scripts/release.sh
Labels: size/M, release-notes-none

#1302 [release-1.23] Makefile: fix bad `fmt` args
  Makefile.core.mk
Labels: size/XS, release-notes-none

#1307 Support inline XDS config and auth
  src/config.rs
  src/identity/auth.rs
Labels: size/L

#1308 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1309 Fix release build regression
  scripts/release.sh
Labels: size/S, release-notes-none

#1304 Validate (and do not set in our test) invalid app_tunnnel
  src/state/workload.rs
  tests/namespaced.rs
Labels: size/S, release-notes-none

#1305 Construct config only when we need it
  src/main.rs
Labels: size/XS, release-notes-none

#1310 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1306 Allow referencing waypoints that are sent as workloads rather than se…
  src/state.rs
  tests/namespaced.rs
Labels: size/M

#1313 When building fuzz tests, build the same way the fuzzer does
  Makefile.core.mk
Labels: size/XS, release-notes-none

#1314 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1312 Revert "Validate (and do not set in our test) invalid app_tunnnel"
  src/state/workload.rs
  tests/namespaced.rs
Labels: size/S

#1316 tls: better error on TLS handshake failures
  src/tls/lib.rs
  src/tls/workload.rs
Labels: size/S, release-notes-none, cherrypick/release-1.23

#1317 [release-1.23] tls: better error on TLS handshake failures
  src/tls/lib.rs
  src/tls/workload.rs
Labels: size/S, release-notes-none

#1298 [release-1.23] Silence new warnings with rust 1.80
  build.rs
Labels: size/XS, release-notes-none

#1318 [release-1.23] Don't create V6 binds if global V6 flag is off
  src/config.rs
  src/dns/server.rs
Labels: size/S, release-notes-none

#1319 Use a per-request backoff for cert fetches, rather than a global one
  src/identity/manager.rs
Labels: size/M

#1324 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1283 Test with coverage
  Makefile.core.mk
  scripts/test-with-coverage.sh
Labels: size/M

#1325 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1326 Automator: update common-files@release-1.21 in istio/ztunnel@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
