Repository istio/ztunnel, pull requests merged in 2024-01, with the labels that each got.

#760 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#761 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#762 Fix lint error
  src/config.rs
Labels: size/XS

#763 add a connect timeout to grpc_connector
  src/tls/boring.rs
Labels: size/XS

#764 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#766 Automator: update common-files@release-1.20 in istio/ztunnel@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#765 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#767 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#769 Automator: update common-files@release-1.20 in istio/ztunnel@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#771 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#747 inpod redirection mode
  Cargo.lock
  Cargo.toml
  LOCAL.md
  build.rs
  fuzz/Cargo.lock
  proto/zds.proto
  scripts/ztunnel-redirect-inpod.sh
  scripts/ztunnel-redirect.sh
  src/admin.rs
  src/app.rs
  src/cert_fetcher.rs
  src/config.rs
  src/dns/server.rs
  src/hyper_util.rs
  src/inpod.rs
  src/inpod/admin.rs
  src/inpod/config.rs
  src/inpod/metrics.rs
  src/inpod/netns.rs
  src/inpod/packet.rs
  src/inpod/protocol.rs
  src/inpod/statemanager.rs
  src/inpod/test_helpers.rs
  src/inpod/workloadmanager.rs
  src/lib.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/socket.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/inpod.rs
  src/test_helpers/linux.rs
  src/test_helpers/netns.rs
  tests/namespaced.rs
Labels: size/XXL

#774 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#778 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#780 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#779 Update the dns crate and add graceful shutdown
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/config.rs
  src/dns/forwarder.rs
  src/dns/handler.rs
  src/dns/metrics.rs
  src/dns/name_util.rs
  src/dns/resolver.rs
  src/dns/server.rs
  src/inpod/test_helpers.rs
  src/proxy/inbound.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/dns.rs
  src/test_helpers/xds.rs
Labels: size/XL

#783 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#784 Update portlist for inpod
  ARCHITECTURE.md
Labels: size/S

#787 cargo build warning
  src/config.rs
Labels: size/S

#786 [release-1.21] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#788 Automator: update common-files@release-1.21 in istio/ztunnel@release-1.21
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#790 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#791 Fix minor typo in statemanager.rs
  src/inpod/statemanager.rs
Labels: size/XS, ok-to-test

#793 Automator: update common-files@master in istio/ztunnel@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
