Repository istio/ztunnel, pull requests merged in 2024-10, with the labels that each got.

#1320 tls: allow alternative hostname verification for control plane
  src/config.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/test_helpers/ca.rs
  src/tls.rs
  src/tls/certificate.rs
  src/tls/control.rs
  src/tls/lib.rs
  src/xds/client.rs
Labels: size/L, release-notes-none

#1328 logging: minor tweaks to debugging
  src/state/service.rs
  src/state/workload.rs
  src/xds.rs
Labels: size/M, release-notes-none

#1330 Prevent `Error` enum from being huge
  src/identity.rs
  src/identity/caclient.rs
Labels: size/XS, release-notes-none

#1332 socks5: slightly improve error reporting
  src/proxy.rs
  src/proxy/socks5.rs
Labels: size/L, release-notes-none

#1331 Reduce stack bloat on inbound
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
Labels: size/M

#1334 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1335 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1338 Bump misc dependencies
  Cargo.lock
  build.rs
  fuzz/Cargo.lock
Labels: release-notes-none, size/XL

#1339 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1342 Fixes for rust 1.81
  src/proxy/socks5.rs
  src/test_helpers/namespaced.rs
  src/test_helpers/tcp.rs
Labels: size/M, release-notes-none

#1343 Align test iptables with what we are using in real code
  scripts/ztunnel-redirect-inpod.sh
Labels: size/XS, release-notes-none

#1344 scripts: early exit if command fails in test coverage
  scripts/test-with-coverage.sh
Labels: size/XS

#1347 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1349 [release-1.24] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#1350 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1352 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1351 [release-1.24] Automated branching step 4
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#1353 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
