Repository istio/ztunnel, pull requests merged in 2024-05, with the labels that each got.

#992 pool: do not indefinitely leak timers
  src/proxy/pool.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#993 [release-1.22] pool: do not indefinitely leak timers
  src/proxy/pool.rs
Labels: size/XS, release-notes-none

#990 Replace hyper with direct `h2` usage for outbound HBONE
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/proxy.rs
  src/proxy/h2_client.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
Labels: size/XXL, release-notes-none, cherrypick/release-1.22

#991 Make connection tracking resiliant to connection reuse
  src/proxy/connection_manager.rs
  src/proxy/outbound.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#997 h2: poll ready before using
  src/proxy/h2_client.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#998 deps: use h2 with race condition fix
  Cargo.lock
  Cargo.toml
Labels: size/S, release-notes-none, cherrypick/release-1.22

#994 [release-1.22] Replace hyper with direct `h2` usage for outbound HBONE
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/proxy.rs
  src/proxy/h2_client.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
Labels: size/XXL, release-notes-none

#995 [release-1.22] Make connection tracking resiliant to connection reuse
  src/proxy/connection_manager.rs
  src/proxy/outbound.rs
Labels: size/L, release-notes-none

#1001 [release-1.22] deps: use h2 with race condition fix
  Cargo.lock
  Cargo.toml
Labels: size/S, release-notes-none

#1003 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1004 Use upstream h2
  Cargo.lock
  Cargo.toml
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#1007 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1006 [release-1.22] Use upstream h2
  Cargo.lock
  Cargo.toml
Labels: size/XS, release-notes-none

#1008 [release-1.22] Miscellanuous optimizations to reduce memory footprint
  src/dns/server.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
Labels: size/L, release-notes-none

#1010 h2: do not use connections that got GoAways
  src/proxy/h2_client.rs
  src/proxy/pool.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1011 [release-1.22] h2: do not use connections that got GoAways
  src/proxy/h2_client.rs
  src/proxy/pool.rs
Labels: size/L, release-notes-none

#1005 [release-1.22] h2: poll ready before using (#997)
  src/proxy/h2_client.rs
Labels: size/XS, release-notes-none

#1017 logs: fix dst.namespace and missing dst.service
  src/proxy/metrics.rs
  tests/namespaced.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#1018 misc: remove Default identity from prod codepath
  src/identity/manager.rs
  src/metrics.rs
Labels: size/S, release-notes-none

#1016 performance: optimized string and various other XDS improvements
  Cargo.lock
  Cargo.toml
  benches/throughput.rs
  fuzz/Cargo.lock
  fuzz/fuzz_targets/protobuf.rs
  src/admin.rs
  src/baggage.rs
  src/cert_fetcher.rs
  src/config.rs
  src/dns/metrics.rs
  src/dns/server.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/lib.rs
  src/metrics.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/rbac.rs
  src/state.rs
  src/state/policy.rs
  src/state/service.rs
  src/state/workload.rs
  src/strng.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/test_helpers/tcp.rs
  src/tls/workload.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/types.rs
  tests/namespaced.rs
Labels: size/XXL, cherrypick/release-1.22

#1014 add missing local example
  Development.md
  examples/inpodserver.rs
  src/test_helpers.rs
Labels: size/M

#1022 1.22: misc cherrypicks
  Cargo.lock
  Cargo.toml
  Development.md
  benches/throughput.rs
  examples/inpodserver.rs
  fuzz/Cargo.lock
  fuzz/fuzz_targets/protobuf.rs
  src/admin.rs
  src/baggage.rs
  src/cert_fetcher.rs
  src/config.rs
  src/dns/metrics.rs
  src/dns/server.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/lib.rs
  src/metrics.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/rbac.rs
  src/state.rs
  src/state/policy.rs
  src/state/service.rs
  src/state/workload.rs
  src/strng.rs
  src/telemetry.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/test_helpers/tcp.rs
  src/tls/workload.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/types.rs
  tests/namespaced.rs
Labels: size/XXL, release-notes-none

#1023 logging: ignore duplicate fields from direct `log` usage
  src/telemetry.rs
Labels: size/XS, release-notes-none

#1024 performance: make copy buffer sizes dynamic
  src/copy.rs
  src/lib.rs
  src/proxy/h2_client.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/socket.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1021 Fix cleaning up identities
  src/cert_fetcher.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/xds.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#1026 [release-1.22] performance: make copy buffer sizes dynamic
  src/copy.rs
  src/lib.rs
  src/proxy/h2_client.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/socket.rs
Labels: size/L, release-notes-none

#1025 [release-1.22] logging: ignore duplicate fields from direct `log` usage
  src/telemetry.rs
Labels: size/XS, release-notes-none

#1027 [release-1.22] Fix cleaning up identities
  src/cert_fetcher.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/xds.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#1028 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1032 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1034 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1029 send HBONE address in PROXY
  benches/throughput.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/test_helpers/tcp.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1037 [release-1.22] send HBONE address in PROXY
  benches/throughput.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/test_helpers/tcp.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#1038 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1035 adopt linting rules for rustc 1.78
  Cargo.toml
  src/state/workload.rs
Labels: size/XS, release-notes-none

#1041 Deflake test_cache_refresh test
  src/identity/manager.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1042 Fix flakes in idempotency test
  src/inpod/statemanager.rs
  src/inpod/test_helpers.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#1045 tests: drop nip.io dependency
  src/test_helpers.rs
  tests/direct.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1050 doc: comment beta status
  README.md
Labels: size/XS

#1048 Make DNS test faster by running parallel
  src/dns/server.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1047 Fix and improve slow test
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1036 Small change to build inpod.
  Development.md
  Makefile.core.mk
Labels: size/XS

#1051 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1046 [release-1.22] tests: drop nip.io dependency
  src/test_helpers.rs
  tests/direct.rs
Labels: size/L, release-notes-none

#1043 [release-1.22] Deflake test_cache_refresh test
  src/identity/manager.rs
Labels: size/M, release-notes-none

#1044 [release-1.22] Fix flakes in idempotency test
  src/inpod/statemanager.rs
  src/inpod/test_helpers.rs
Labels: size/S, release-notes-none

#1053 [release-1.22] Fix and improve slow test
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/M, release-notes-none

#1056 dns: fix headless service handling
  src/dns/server.rs
  src/state.rs
  src/state/service.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1059 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1058 [release-1.22] dns: fix headless service handling
  src/dns/server.rs
  src/state.rs
  src/state/service.rs
Labels: size/L, release-notes-none

#1060 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1062 perf: really, really stop nagle's algorithm
  src/dns/server.rs
  src/inpod/config.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/socket.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1057 h2/fix dropper
  src/proxy/h2.rs
  src/proxy/h2/client.rs
  src/proxy/h2/server.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1066 [release-1.22] perf: really, really stop nagle's algorithm
  src/dns/server.rs
  src/inpod/config.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/socket.rs
Labels: size/L, release-notes-none

#1067 Better handling of proxying shutdown
  src/copy.rs
  src/proxy.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1068 [release-1.22] Better handling of proxying shutdown
  src/copy.rs
  src/proxy.rs
Labels: size/M, release-notes-none

#1069 deps: use released `h2`
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1071 logs: faster and more correct JSON format
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/main.rs
  src/proxy/outbound.rs
  src/telemetry.rs
  tests/namespaced.rs
Labels: size/L, cherrypick/release-1.22

#1054 allow missing svc port for sandwich
  src/state.rs
  tests/namespaced.rs
Labels: size/L

#1075 Fully remove public internet dependency on DNS tests
  src/dns/forwarder.rs
  src/dns/server.rs
  src/proxyfactory.rs
  src/telemetry.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/dns.rs
  tests/direct.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1078 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1081 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1073 [release-1.22] logs: faster and more correct JSON format
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/main.rs
  src/proxy/outbound.rs
  src/telemetry.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#1080 [release-1.22] add logging for xds nack errors
  src/xds/client.rs
Labels: size/S, release-notes-none

#1040 Cleanup `illegal_ports` and ARC all of PI
  src/config.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/test_helpers.rs
Labels: size/L

#1082 Refactor build_requests
  benches/throughput.rs
  src/app.rs
  src/dns/server.rs
  src/inpod/test_helpers.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/xds.rs
  src/xds/client.rs
Labels: release-notes-none, size/XL, cherrypick/release-1.22

#1088 Don't use trust_domain in zds
  proto/zds.proto
  src/inpod/admin.rs
  src/inpod/protocol.rs
  src/inpod/statemanager.rs
  src/state.rs
Labels: size/S

#1091 [release-1.22] Don't use trust_domain in zds
  proto/zds.proto
  src/inpod/admin.rs
  src/inpod/protocol.rs
  src/inpod/statemanager.rs
  src/state.rs
Labels: size/S, release-notes-none

#1093 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1085 Fix regression in source IP spoofing
  src/config.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
Labels: size/M

#1072 [1.22] deps: use released `h2` (#1069)
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
Labels: size/M, release-notes-none

#1090 Fully remove public internet dependency on DNS tests (#1075)
  src/dns/forwarder.rs
  src/dns/server.rs
  src/proxyfactory.rs
  src/telemetry.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/dns.rs
  tests/direct.rs
Labels: size/L, release-notes-none

#1094 Do not expose internal rustls errors to users
  src/copy.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#1100 [release-1.22] Do not expose internal rustls errors to users
  src/copy.rs
Labels: size/S, release-notes-none

#1101 Remove developer logs
  src/proxy/pool.rs
Labels: size/XS, release-notes-none

#1102 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1103 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1086 mertics: derive identity from TLS handshake
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/telemetry.rs
  tests/namespaced.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22
