Repository istio/ztunnel, pull requests merged in 2024-03, with the labels that each got.

#834 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#833 Revert Add retry backoff to cert refresh (#768)
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/M

#838 logging: allow json format
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/telemetry.rs
Labels: size/M, release-notes-none

#840 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#841 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#843 Automator: update common-files@release-1.20 in istio/ztunnel@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#839 metrics: minor improvements, documentation, and stability levels
  README.md
  src/dns/metrics.rs
  src/inpod/metrics.rs
  src/proxy/metrics.rs
  src/test_helpers/app.rs
  src/xds/metrics.rs
  tests/direct.rs
Labels: size/L, release-notes-none

#844 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#845 Fix some typo about flag
  README.md
  src/app.rs
Labels: size/XS, ok-to-test

#847 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#848 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#849 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#832 service addressed waypoint
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state/service.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  tests/namespaced.rs
Labels: size/L

#789 basic sandwich
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
Labels: size/XL

#853 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#857 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#835 Add retry backoff to cert refresh
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/M

#858 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#855 fix service addressed traffic
  src/proxy/inbound.rs
  src/proxy/outbound.rs
Labels: size/S

#860 Update rustls
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
Labels: size/L
