Repository istio/ztunnel, pull requests merged in 2024-11, with the labels that each got.

#1355 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1354 Initial support for build caching with rust
  scripts/run-cached.sh
Labels: size/M, release-notes-none

#1357 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1359 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1364 Indicate ztunnel is now GA
  README.md
Labels: size/XS, release-notes-none, cherrypick/release-1.24

#1365 [release-1.24] Indicate ztunnel is now GA
  README.md
Labels: size/XS, release-notes-none

#1366 Make loop protection more robust
  src/config.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/test_helpers/linux.rs
  tests/namespaced.rs
Labels: size/M, release-notes-none, cherrypick/release-1.24

#1367 [release-1.24] Make loop protection more robust
  src/config.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/test_helpers/linux.rs
  tests/namespaced.rs
Labels: size/M, release-notes-none

#1369 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1368 xds: gracefully handle stream termination without error
  src/xds/client.rs
Labels: size/S, release-notes-none, cherrypick/release-1.24

#1370 [release-1.24] xds: gracefully handle stream termination without error
  src/xds/client.rs
Labels: size/S, release-notes-none

#1361 adjust metrics content-type
  src/metrics/server.rs
Labels: size/M
