Repository istio/ztunnel, pull requests merged in 2024-08, with the labels that each got.

#1243 [release-1.22] Minimal fix to build on rust 1.80
  Cargo.toml
  fuzz/Cargo.lock
  src/state/workload.rs
  src/strng.rs
Labels: size/S, release-notes-none

#1246 [release-1.23] Support hostname waypoints
  src/proxy/outbound.rs
  src/state.rs
  src/test_helpers/linux.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#1249 copy: fix handling of blocked writers
  src/copy.rs
Labels: size/L, release-notes-none, cherrypick/release-1.23

#1250 [release-1.23] copy: fix handling of blocked writers
  src/copy.rs
Labels: size/L, release-notes-none

#1252 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1253 Fix regression in waypoints to use original IP
  src/proxy/outbound.rs
  src/state.rs
Labels: size/M, release-notes-none, cherrypick/release-1.23

#1254 [release-1.23] Fix regression in waypoints to use original IP
  src/proxy/outbound.rs
  src/state.rs
Labels: size/M, release-notes-none

#1255 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1256 More consistent logging for inpod
  src/inpod.rs
  src/inpod/statemanager.rs
  src/inpod/workloadmanager.rs
Labels: size/M, release-notes-none, cherrypick/release-1.23

#1258 Automator: update common-files@release-1.22 in istio/ztunnel@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1259 Automator: update common-files@release-1.23 in istio/ztunnel@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1257 [release-1.23] More consistent logging for inpod
  src/inpod.rs
  src/inpod/statemanager.rs
  src/inpod/workloadmanager.rs
Labels: size/M, release-notes-none

#1248 remove authorization from "by_namespace" when scope change to workload
  benches/throughput.rs
  src/app.rs
  src/proxy/connection_manager.rs
  src/state/policy.rs
  src/xds.rs
Labels: size/M, ok-to-test

#1261 add json header to config dump, so the browser renders it nicely
  src/admin.rs
Labels: size/XS

#1262 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1264 Bump various dependencies
  Cargo.lock
Labels: size/L, release-notes-none

#1263 Update tests to use REDIRECT instead of TPROXY
  scripts/ztunnel-redirect-inpod.sh
  tests/namespaced.rs
Labels: size/S, release-notes-none

#1266 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1267 Automator: update common-files@release-1.23 in istio/ztunnel@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1270 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1271 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1269 Improvements to Endpoint handling
  src/admin.rs
  src/dns/server.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/xds.rs
Labels: size/L, release-notes-none

#1273 rbac - include policy name in rejection logs
  benches/throughput.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/state.rs
  src/xds/client.rs
  tests/namespaced.rs
Labels: size/L

#1275 Don't create V6 binds if global V6 flag is off
  src/config.rs
  src/dns/server.rs
Labels: size/S

#1274 Optimize XDS surrounding workload updates
  Cargo.toml
  benches/basic.rs
  src/proxy.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/xds.rs
Labels: size/L

#1276 Cleanup redirection scripts
  scripts/node-redirect.sh
  scripts/tproxy.sh
  scripts/ztunnel-redirect.sh
Labels: size/L, release-notes-none

#1218 Fetch local workload directly, rather than based on IP
  Cargo.lock
  Cargo.toml
  Development.md
  benches/basic.rs
  benches/throughput.rs
  examples/inpodserver.rs
  fuzz/Cargo.lock
  src/admin.rs
  src/app.rs
  src/cert_fetcher.rs
  src/config.rs
  src/identity.rs
  src/identity/manager.rs
  src/inpod/admin.rs
  src/inpod/statemanager.rs
  src/inpod/test_helpers.rs
  src/inpod/workloadmanager.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/h2/server.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/inpod.rs
  src/test_helpers/linux.rs
  src/test_helpers/xds.rs
  src/tls/lib.rs
  src/tls/mock.rs
  src/tls/workload.rs
  src/xds.rs
  src/xds/client.rs
  tests/namespaced.rs
Labels: size/XXL, release-notes-none

#1278 Fix incorrect function naming
  src/config.rs
  src/proxy.rs
Labels: size/XS, release-notes-none

#1277 Document json logging
  README.md
Labels: size/XS, release-notes-none

#1280 dns: use new local workload fetch
  src/dns/server.rs
  src/proxy.rs
  src/proxyfactory.rs
  src/test_helpers/dns.rs
Labels: size/L, release-notes-none

#1279 test: show how to enter user namespace as well
  src/test_helpers/namespaced.rs
Labels: size/XS, release-notes-none

#1282 dns: forward requests from the pod workload
  src/dns/forwarder.rs
  src/dns/server.rs
  src/proxyfactory.rs
  src/test_helpers/dns.rs
Labels: size/M, release-notes-none

#1284 zds: fix retrying a bad netns
  src/inpod/statemanager.rs
Labels: size/M, release-notes-none, cherrypick/release-1.23

#1285 [release-1.23] zds: fix retrying a bad netns
  src/inpod/statemanager.rs
Labels: size/M, release-notes-none

#1286 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
