Repository istio/ztunnel, pull requests merged in 2024-07, with the labels that each got.

#1190 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1192 Automator: update common-files@release-1.21 in istio/ztunnel@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1193 Automator: update common-files@release-1.22 in istio/ztunnel@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1195 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1176 Abstract and fix draining
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/admin.rs
  src/app.rs
  src/dns/server.rs
  src/drain.rs
  src/hyper_util.rs
  src/inpod/protocol.rs
  src/inpod/statemanager.rs
  src/inpod/test_helpers.rs
  src/inpod/workloadmanager.rs
  src/lib.rs
  src/metrics/server.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/h2/server.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/readiness/server.rs
  src/signal.rs
  src/test_helpers/dns.rs
  src/test_helpers/inpod.rs
  src/test_helpers/linux.rs
  src/test_helpers/netns.rs
  tests/direct.rs
  tests/namespaced.rs
Labels: size/XXL, release-notes-none

#1031 combine `proxymode = shared` and `inpod_mode = true`
  Development.md
  benches/throughput.rs
  src/app.rs
  src/config.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  tests/namespaced.rs
Labels: size/L

#1197 Remove TODO'd case for ProxyMode::Dedicated that is no longer relevant
  src/proxy/outbound.rs
Labels: size/XS

#1201 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1200 Drop unused struct
  src/inpod/metrics.rs
Labels: size/XS, release-notes-none

#1170 dependencies: update to tonic 0.12
  Cargo.lock
  Cargo.toml
  deny.toml
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  src/hyper_util.rs
  src/identity/caclient.rs
  src/inpod/protocol.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/ca.rs
  src/test_helpers/hyper_tower.rs
  src/test_helpers/xds.rs
  src/tls/control.rs
Labels: release-notes-none, size/XL

#1202 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1199 Trace tokio spawns when using Hyper
  src/hyper_util.rs
Labels: size/XS, release-notes-none

#1204 Update development instructions for local development
  Development.md
Labels: size/S

#1207 Update instructions for Kind setup
  Development.md
Labels: size/S

#1205 More XDS metrics
  src/xds/client.rs
  src/xds/metrics.rs
Labels: size/M

#1210 [release-1.23] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#1211 Automator: update common-files@release-1.23 in istio/ztunnel@release-1.23
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1212 add context to inpod::workloadmager failed to connect log message
  src/inpod/workloadmanager.rs
Labels: size/XS

#1213 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1209 Disable IP spoofing on outbound
  scripts/ztunnel-redirect.sh
  src/config.rs
  src/inpod/config.rs
  src/inpod/test_helpers.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/test_helpers/netns.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none, cherrypick/release-1.23

#1215 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1214 [release-1.23] Disable IP spoofing on outbound
  scripts/ztunnel-redirect.sh
  src/config.rs
  src/inpod/config.rs
  src/inpod/test_helpers.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/test_helpers/netns.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#1220 Fix test that takes 5s
  src/proxy/outbound.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22, cherrypick/release-1.23

#1221 [release-1.22] Fix test that takes 5s
  src/proxy/outbound.rs
Labels: size/XS, release-notes-none

#1219 [1.22] Improve logging of errors in copy (#1188)
  src/copy.rs
  src/proxy.rs
Labels: size/M, release-notes-none

#1223 Automator: update common-files@master in istio/ztunnel@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1222 [release-1.23] Fix test that takes 5s
  src/proxy/outbound.rs
Labels: size/XS, release-notes-none

#1216 Add support for hostnetwork pods
  proto/workload.proto
  src/admin.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/xds.rs
Labels: size/L, release-notes-none

#1226 Enable DNS server by default
  src/config.rs
  src/inpod/test_helpers.rs
Labels: size/XS, release-notes-none

#1229 Add warning log to check NetworkPolicy for 15008 denial
  src/proxy.rs
  src/proxy/pool.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22, cherrypick/release-1.23

#1230 Fix inconsistency in inbound dst.addr logging
  src/proxy/inbound.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#1234 [release-1.23] Fix inconsistency in inbound dst.addr logging
  src/proxy/inbound.rs
Labels: size/XS, release-notes-none

#1233 [release-1.23] Add warning log to check NetworkPolicy for 15008 denial
  src/proxy.rs
  src/proxy/pool.rs
Labels: size/S, release-notes-none

#1235 [Direct to 1.23] Future proof LoadBalancerPolicy
  src/state.rs
  src/state/service.rs
Labels: size/S, release-notes-none

#1236 [release-1.22] Add warning log to check NetworkPolicy for 15008 denial
  src/proxy.rs
  src/proxy/pool.rs
Labels: size/S, release-notes-none

#1237 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1227 Make docs tests not fail
  src/test_helpers/namespaced.rs
Labels: size/XS, release-notes-none

#1238 Improve XDS error diagnostics
  src/xds.rs
  src/xds/client.rs
Labels: size/S, release-notes-none, cherrypick/release-1.23

#1242 Minimal fix to build on rust 1.80
  Cargo.toml
  fuzz/Cargo.lock
  src/strng.rs
Labels: size/S, release-notes-none

#1240 [release-1.23] Improve XDS error diagnostics
  src/xds.rs
  src/xds/client.rs
Labels: size/S, release-notes-none

#1244 Use dev + inode to identify/compare netns
  src/inpod/netns.rs
  src/inpod/statemanager.rs
Labels: size/M

#1239 [release-1.23] Enable DNS server by default
  src/config.rs
  src/inpod/test_helpers.rs
Labels: size/XS, release-notes-none

#1231 Add support for `publishNotReadyAddresses`
  proto/workload.proto
  src/admin.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/xds.rs
Labels: size/L, release-notes-none
