Repository istio/ztunnel, pull requests merged in 2024-04, with the labels that each got.

#850 proxy protocol for sandwich
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  proto/workload.proto
  src/admin.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/rbac.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/xds/client.rs
Labels: size/L

#867 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#866 Bump rust dependencies
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/identity.rs
  src/inpod/packet.rs
  src/tls.rs
  src/tls/csr.rs
  src/tls/lib.rs
  src/tls/mock.rs
Labels: size/L, release-notes-none

#869 h2: set max header size
  src/proxy/inbound.rs
Labels: size/XS, release-notes-none

#875 xds: gracefully handle decode errors
  src/xds/client.rs
Labels: size/M, release-notes-none

#868 Implement locality aware load balancing
  proto/workload.proto
  src/admin.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/xds.rs
Labels: release-notes-none, size/XL

#881 fix dumping application protocol
  src/state/workload.rs
Labels: size/XS

#882 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/M, auto-merge, release-notes-none

#885 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#887 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#890 Automator: update common-files@release-1.20 in istio/ztunnel@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#891 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/M, auto-merge, release-notes-none

#893 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#894 Ensure some spawns have deadlines
  Cargo.lock
  Cargo.toml
  Makefile.core.mk
  fuzz/Cargo.lock
  src/proxy/inbound.rs
  src/telemetry.rs
Labels: size/L

#895 Drop priority queue dependency with bad license
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/identity/manager.rs
Labels: size/M, release-notes-none

#880 handle various usage of unwrap to proper error handling
  src/admin.rs
  src/hyper_util.rs
  src/identity/manager.rs
  src/metrics/server.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/tls/certificate.rs
  src/tls/control.rs
  src/tls/workload.rs
Labels: size/L, release-notes-none

#883 admin: add connection info dump
  src/identity/manager.rs
  src/inpod/admin.rs
  src/inpod/statemanager.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxyfactory.rs
  src/rbac.rs
  src/state.rs
Labels: size/L, release-notes-none

#879 Get `cargo deny` passing
  deny.toml
Labels: size/L, release-notes-none

#884 e2e: use less clients where possible
  tests/namespaced.rs
Labels: size/M, release-notes-none

#886 pool: include source IP in key
  src/proxy/outbound.rs
  src/proxy/pool.rs
Labels: size/XS, release-notes-none

#898 Implement outbound drain
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
Labels: size/L

#901 README: add arch entry
  README.md
Labels: size/XS

#906 update features
  Cargo.toml
Labels: size/XS

#908 inbound: drop logic to spoof IP from Forwarded
  src/proxy.rs
  src/proxy/inbound.rs
Labels: size/M, release-notes-none

#911 tls: drop certificates we don't care about anymore
  src/cert_fetcher.rs
  src/identity/manager.rs
  src/state/workload.rs
  src/xds.rs
Labels: size/L, release-notes-none

#905 LOCAL: update command
  LOCAL.md
Labels: size/XS

#910 tls: avoid setting CN in CSR
  src/tls/csr.rs
Labels: size/M, release-notes-none

#897 pool: ignore source port
  src/proxy/outbound.rs
  src/proxy/pool.rs
Labels: size/XS, release-notes-none

#907 logs: hide dns logs by default
  src/admin.rs
  src/telemetry.rs
Labels: size/M, release-notes-none

#916 version: include profile name
  build.rs
  src/version.rs
Labels: size/S, release-notes-none

#871 Move log format to standard Istio format
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/telemetry.rs
Labels: size/L, release-notes-none

#874 Initial access logs implementation
  README.md
  src/metrics.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
Labels: size/XXL, release-notes-none

#919 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#914 admin: add workload info to admin dump
  src/inpod/admin.rs
  src/inpod/statemanager.rs
  src/proxy/connection_manager.rs
  src/state.rs
Labels: size/M, release-notes-none

#920 admin: use camel case and omit defaults in more places
  src/state/service.rs
  src/state/workload.rs
Labels: size/XS, release-notes-none

#921 config: Replace "status_port" with "stats_port".
  src/config.rs
  src/test_helpers/mesh_config.yaml
Labels: size/XS

#903 README: add rust version comment
  Cargo.toml
  Makefile.core.mk
  README.md
Labels: size/S

#900 README: add development entry
  Development.md
  README.md
Labels: size/M

#924 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#925 admin: fix last camel case
  src/rbac.rs
Labels: size/XS, release-notes-none

#930 A few minor docs changes.
  README.md
  src/dns/metrics.rs
Labels: size/S

#927 Periodic metrics reporting
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/socket.rs
Labels: size/L, release-notes-none

#936 dns: remove unbounded cardinality in metrics
  src/dns/metrics.rs
  src/dns/server.rs
Labels: size/M, release-notes-none

#938 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#937 admin: make extended handlers inline into `/config_dump`
  src/admin.rs
  src/inpod/admin.rs
  src/test_helpers/app.rs
Labels: size/L, release-notes-none

#935 block illegal calls in inpod mode
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
Labels: size/M, release-notes-none

#941 Bump dependencies in prep for 1.22
  Cargo.lock
  deny.toml
Labels: size/L, release-notes-none

#933 fix unknown field in testing yaml due to camel case change
  examples/localhost.yaml
Labels: size/XS, release-notes-none

#939 Track outbound connections
  src/inpod/admin.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/test_helpers/app.rs
Labels: size/L, release-notes-none

#943 Make socks5 optional, off by default
  src/config.rs
  src/proxy.rs
  src/proxy/socks5.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
  tests/direct.rs
Labels: size/M, release-notes-none

#951 [release-1.22] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#946 metrics: Don't log 'hbone_target' as a string.
  README.md
  src/proxy/metrics.rs
Labels: size/XS

#953 [release-1.22] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#954 Automator: update common-files@release-1.22 in istio/ztunnel@release-1.22
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#940 metrics: make traffic metrics faster
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/socket.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#942 Pass original service over HBONE for debugging
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#956 metrics: add flag for deny by policy
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#947 [release-1.22] fix unknown field in testing yaml due to camel case change
  examples/localhost.yaml
Labels: size/XS, release-notes-none

#948 [release-1.22] Track outbound connections
  src/inpod/admin.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/test_helpers/app.rs
Labels: size/L, release-notes-none

#949 [release-1.22] Bump rustls from 0.23.4 to 0.23.5 in /fuzz
  fuzz/Cargo.lock
Labels: size/XS, release-notes-none

#950 [release-1.22] Make socks5 optional, off by default
  src/config.rs
  src/proxy.rs
  src/proxy/socks5.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
  tests/direct.rs
Labels: size/M, release-notes-none

#963 metrics: make traffic metrics faster (#940)
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/socket.rs
Labels: size/L, release-notes-none

#964 Pass original service over HBONE for debugging (#942)
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
Labels: size/L, release-notes-none

#966 Stop denying 15008 for sandwich case
  src/proxy/inbound.rs
Labels: release-notes-none, cherrypick/release-1.22

#962 test: run `namespaced` tests without root
  Cargo.lock
  Cargo.toml
  Development.md
  Makefile.core.mk
  tests/namespaced.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#969 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#965 [release-1.22] metrics: add flag for deny by policy (#956)
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
Labels: size/S, release-notes-none

#967 [release-1.22] Stop denying 15008 for sandwich case
  src/proxy/inbound.rs
Labels: size/XS, release-notes-none

#959 rbac: log unknown policies for debugging purposes
  src/state.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#970 Implement better "namespaced" tests
  scripts/node-redirect.sh
  scripts/ztunnel-redirect-inpod.sh
  src/config.rs
  src/dns/forwarder.rs
  src/dns/handler.rs
  src/dns/server.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/state/policy.rs
  src/telemetry.rs
  src/test_helpers.rs
  src/test_helpers/helpers.rs
  src/test_helpers/inpod.rs
  src/test_helpers/linux.rs
  src/test_helpers/netns.rs
  src/test_helpers/tcp.rs
  src/tls/workload.rs
  src/xds.rs
  tests/direct.rs
  tests/namespaced.rs
Labels: size/XXL, cherrypick/release-1.22

#973 Test sandwiched waypoint
  benches/throughput.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/test_helpers/linux.rs
  src/test_helpers/tcp.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#977 Support running tests in docker
  Makefile.overrides.mk
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#975 [release-1.22] Implement better "namespaced" tests
  scripts/node-redirect.sh
  scripts/ztunnel-redirect-inpod.sh
  src/config.rs
  src/dns/forwarder.rs
  src/dns/handler.rs
  src/dns/server.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/state/policy.rs
  src/telemetry.rs
  src/test_helpers.rs
  src/test_helpers/helpers.rs
  src/test_helpers/inpod.rs
  src/test_helpers/linux.rs
  src/test_helpers/netns.rs
  src/test_helpers/tcp.rs
  src/tls/workload.rs
  src/xds.rs
  tests/direct.rs
  tests/namespaced.rs
Labels: size/XXL, release-notes-none

#974 [release-1.22] rbac: log unknown policies for debugging purposes
  src/state.rs
Labels: size/S, release-notes-none

#978 [release-1.22] Support running tests in docker
  Makefile.overrides.mk
Labels: size/XS, release-notes-none

#979 Verify workload consistency with CNI for outbound
  src/proxy.rs
  src/proxy/outbound.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#981 [release-1.22] Verify workload consistency with CNI for outbound
  src/proxy.rs
  src/proxy/outbound.rs
Labels: size/XS, release-notes-none

#972 admin: support setting log of a specific scope
  src/admin.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#931 Better-behaved HBONE pooling
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/admin.rs
  src/config.rs
  src/identity/manager.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
Labels: size/XXL, cherrypick/release-1.22

#984 [release-1.22] Test sandwiched waypoint
  benches/throughput.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/test_helpers/linux.rs
  src/test_helpers/tcp.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#983 [release-1.22] Better-behaved HBONE pooling
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/admin.rs
  src/config.rs
  src/identity/manager.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
Labels: size/XXL, release-notes-none

#982 [release-1.22] admin: support setting log of a specific scope
  src/admin.rs
Labels: size/M, release-notes-none

#980 Fix build for jemalloc feature
  Makefile.core.mk
  src/admin.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#986 [release-1.22] Fix build for jemalloc feature
  Makefile.core.mk
  src/admin.rs
Labels: size/S, release-notes-none

#987 logging: disable regex
  src/admin.rs
  src/telemetry.rs
Labels: size/M, release-notes-none

#985 performance: reduce and test size of futures
  Cargo.toml
  benches/throughput.rs
  fuzz/Cargo.lock
  src/admin.rs
  src/app.rs
  src/assertions.rs
  src/identity/manager.rs
  src/inpod/test_helpers.rs
  src/lib.rs
  src/main.rs
  src/metrics/server.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/readiness/server.rs
  src/state.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
  src/test_helpers/xds.rs
  src/xds/client.rs
  tests/direct.rs
Labels: release-notes-none, size/XL, cherrypick/release-1.22

#989 [release-1.22] performance: reduce and test size of futures
  Cargo.toml
  benches/throughput.rs
  fuzz/Cargo.lock
  src/admin.rs
  src/app.rs
  src/assertions.rs
  src/identity/manager.rs
  src/inpod/test_helpers.rs
  src/lib.rs
  src/main.rs
  src/metrics/server.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/readiness/server.rs
  src/state.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
  src/test_helpers/xds.rs
  src/xds/client.rs
  tests/direct.rs
Labels: release-notes-none, size/XL
