Repository istio/ztunnel, pull requests merged in 2024-06, with the labels that each got.

#1105 [release-1.22] mertics: derive identity from TLS handshake
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/telemetry.rs
  tests/namespaced.rs
Labels: size/M, release-notes-none

#1107 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#1108 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1097 refactor: use now-stable stdlib to_canonical
  src/socket.rs
Labels: size/S, release-notes-none

#1098 dns: drop (unneeded) on-demand DNS caching
  README.md
  src/config.rs
  src/proxy/metrics.rs
  src/state.rs
  tests/direct.rs
Labels: size/L, release-notes-none

#1109 Make conn termination deadline configurable
  src/config.rs
Labels: size/S

#1096 socks5: add initial hostname lookup support
  benches/throughput.rs
  src/dns/server.rs
  src/proxy.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
  src/test_helpers/app.rs
  tests/direct.rs
Labels: size/L, release-notes-none

#1095 access logs: consistently quote fields
  src/admin.rs
  src/metrics.rs
  src/proxy/metrics.rs
  src/state.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1092 Fix outbound race condition where we don't have the source workload from XDS yet
  src/proxy/outbound.rs
  src/state.rs
  src/state/workload.rs
  src/telemetry.rs
  src/xds/client.rs
Labels: size/L, cherrypick/release-1.22

#1099 dns: fix search lookup
  src/dns/server.rs
  src/proxyfactory.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1113 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1110 [release-1.22] access logs: consistently quote fields
  src/admin.rs
  src/metrics.rs
  src/proxy/metrics.rs
  src/state.rs
Labels: size/M, release-notes-none

#1111 [release-1.22] Fix outbound race condition where we don't have the source workload from XDS yet
  src/proxy/outbound.rs
  src/state.rs
  src/state/workload.rs
  src/xds/client.rs
Labels: size/L, release-notes-none

#1115 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1116 Automator: update common-files@release-1.20 in istio/ztunnel@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1118 [release-1.22] dns: fix search lookup
  src/dns/server.rs
  src/proxyfactory.rs
Labels: size/L

#1114 identity: triple check proxies can only request appropriate certificates
  src/identity.rs
  src/identity/manager.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
Labels: size/M, release-notes-none

#1120 Drop improper workload DNS lookups
  src/dns/server.rs
  src/state.rs
  src/state/workload.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1121 Remove unused Workload field
  src/proxy.rs
  src/state/workload.rs
  src/test_helpers.rs
Labels: size/S, release-notes-none

#1125 logs: do not allocate absurd buffers
  src/telemetry.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#1126 [release-1.22] logs: do not allocate absurd buffers
  src/telemetry.rs
Labels: size/XS, release-notes-none

#1123 Drop improper workload DNS lookups (#1120)
  src/dns/server.rs
  src/state.rs
  src/state/workload.rs
Labels: size/M, release-notes-none

#1129 h2: remove illegal double oneshot recv
  src/hyper_util.rs
  src/proxy/h2/server.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#1132 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1133 Automator: update common-files@release-1.21 in istio/ztunnel@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1134 Automator: update common-files@release-1.22 in istio/ztunnel@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1135 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1137 Drop requests to service without any backends
  src/proxy.rs
  src/proxy/outbound.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#1138 Improve error log output format
  src/proxy/metrics.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#1141 nit: Should be debug
  src/xds/client.rs
Labels: size/XS

#1142 Properly handle named targetPort services
  src/proxy/outbound.rs
  src/state.rs
  src/state/workload.rs
Labels: size/L, release-notes-none, cherrypick/release-1.22

#1146 Make xds wait longer (500ms -> 5s)
  src/proxy/outbound.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#1143 Drop IP spoofing for outbound traffic
  src/proxy/outbound.rs
  src/proxy/socks5.rs
Labels: size/S, release-notes-none

#1144 Hide error logs when peer shut's down for us
  src/copy.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#1149 [release-1.22] Hide error logs when peer shut's down for us
  src/copy.rs
Labels: size/S, release-notes-none

#1139 [release-1.22] Drop requests to service without any backends
  src/proxy.rs
  src/proxy/outbound.rs
Labels: size/S, release-notes-none

#1140 [release-1.22] Improve error log output format
  src/proxy/metrics.rs
Labels: size/XS, release-notes-none

#1147 [release-1.22] Make xds wait longer (500ms -> 5s)
  src/proxy/outbound.rs
Labels: size/XS, release-notes-none

#1150 Remove mutex on copy path
  src/copy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
Labels: size/M, release-notes-none

#1151 Make benchmarks a bit more consistent and realistic
  Cargo.toml
  benches/throughput.rs
  src/inpod/workloadmanager.rs
  src/test_helpers.rs
  src/test_helpers/namespaced.rs
  src/test_helpers/netns.rs
  src/test_helpers/tcp.rs
  tests/namespaced.rs
Labels: release-notes-none, size/XL

#1148 [release-1.22] Properly handle named targetPort services
  src/proxy/outbound.rs
  src/state.rs
  src/state/workload.rs
Labels: size/L, release-notes-none

#1154 dns: bind to ipv4 and ipv6
  src/config.rs
  src/dns/server.rs
  src/test_helpers.rs
Labels: size/L, release-notes-none

#1156 outbound: when calling pod IP directly, always use that pod IP
  src/proxy/outbound.rs
  src/state.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1159 Drop unused field in WDS
  proto/workload.proto
  src/admin.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
Labels: size/M, release-notes-none

#1157 drain: give 5s (configurable) time for existing connections to gracefully close
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
Labels: size/M, release-notes-none

#1136 Chill out at the proto level as well as the socket level if we have issues connecting to the ambient node agent.
  src/inpod/workloadmanager.rs
Labels: size/S

#1158 [release-1.22] outbound: when calling pod IP directly, always use that pod IP
  src/proxy/outbound.rs
  src/state.rs
Labels: size/M, release-notes-none

#1163 Add option for disabling IPv6
  src/config.rs
  src/dns/server.rs
  src/test_helpers.rs
  src/test_helpers/dns.rs
Labels: size/M, release-notes-none, cherrypick/release-1.22

#1162 Allow running inpod on musl build
  src/inpod/packet.rs
Labels: size/XS, release-notes-none

#1161 Support ip_families field in service
  proto/workload.proto
  src/admin.rs
  src/dns/server.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
Labels: size/L, release-notes-none

#1168 Minor logging cleanup
  src/copy.rs
  src/inpod/statemanager.rs
  src/proxy.rs
  src/proxy/h2/client.rs
  src/proxy/inbound.rs
  src/proxy/pool.rs
Labels: size/L, release-notes-none

#1166 Add option for disabling IPv6 (#1163)
  src/config.rs
Labels: size/S, release-notes-none

#1169 Optimize throughput
  Cargo.lock
  Cargo.toml
  benches/README.md
  fuzz/Cargo.lock
  src/copy.rs
  src/proxy/h2.rs
  src/proxy/h2/client.rs
  src/proxy/h2/server.rs
  src/proxy/inbound_passthrough.rs
Labels: size/L, release-notes-none

#1165 admin: bind to both IP families
  src/config.rs
  src/hyper_util.rs
  src/test_helpers.rs
  tests/direct.rs
Labels: size/L, release-notes-none

#1172 Invert IPv6 flag for consistency:
  src/config.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#1173 [release-1.22] Invert IPv6 flag for consistency:
  src/config.rs
Labels: size/XS, release-notes-none

#1171 benchmarks: benchmark various levels of concurrency
  benches/throughput.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
Labels: size/L

#1175 h2: avoid excessive buffer size
  src/proxy/h2/client.rs
Labels: size/XS, release-notes-none

#1180 Better proto err logging/announce retries
  src/inpod.rs
  src/inpod/protocol.rs
  src/inpod/statemanager.rs
  src/inpod/workloadmanager.rs
Labels: size/L

#1181 nit: drop extra log
  src/inpod/workloadmanager.rs
Labels: size/XS

#1179 Fix edge case in delayed workload case
  src/state.rs
Labels: size/S, release-notes-none, cherrypick/release-1.22

#1182 [release-1.22] Fix edge case in delayed workload case
  src/state.rs
Labels: size/S, release-notes-none

#1185 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1186 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1184 Drain: allow more dynamic configuration
  src/config.rs
Labels: size/M, release-notes-none

#1187 Keep track of logs for terminated connections
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
Labels: size/M, release-notes-none

#1178 Conditionally bind to localhost for partial IPv6 support
  src/config.rs
  src/dns/server.rs
  src/inpod/config.rs
  src/proxy.rs
Labels: size/M, release-notes-none

#1188 Improve logging of errors in copy
  src/copy.rs
  src/proxy.rs
  src/proxy/inbound_passthrough.rs
Labels: size/M, release-notes-none

#1189 Add more context on statemanager logs
  src/inpod/statemanager.rs
Labels: size/S, release-notes-none
