Repository istio/ztunnel, pull requests merged in 2024-02, with the labels that each got.

#794 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#772 close connections which violate policy after updates
  src/identity/manager.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/rbac.rs
  src/state/policy.rs
  src/xds.rs
Labels: size/XL

#799 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#800 Bump to nix-0.27.1
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/inpod/config.rs
  src/inpod/netns.rs
  src/inpod/packet.rs
  src/inpod/protocol.rs
Labels: size/M

#801 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#806 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#807 Automator: update common-files@release-1.19 in istio/ztunnel@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#810 Automator: update common-files@master in istio/ztunnel@master
  SUPPORT.md
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#811 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#812 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#813 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#814 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#768 Add retry backoff to cert refresh
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/L

#822 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#823 Add waypoint to Service proto definition in WDS
  proto/workload.proto
  src/admin.rs
  src/state/workload.rs
Labels: size/XS

#804 initial improvements for connection_manager
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/proxyfactory.rs
Labels: size/L

#726 dependendencies: bump to hyper 1.0.0
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  src/config.rs
  src/hyper_util.rs
  src/proxy.rs
  src/proxy/pool.rs
  src/rbac.rs
  src/state/workload.rs
  src/test_helpers/xds.rs
  src/tls/boring.rs
Labels: size/XXL, lifecycle/automatically-closed

#825 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#827 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb-native.yaml
Labels: size/L, auto-merge, release-notes-none

#828 Automator: update common-files@release-1.20 in istio/ztunnel@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#829 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#777 proxy: validate ZDS provided workload service account when asserting rbac
  Cargo.toml
  proto/zds.proto
  src/inpod.rs
  src/inpod/protocol.rs
  src/inpod/statemanager.rs
  src/inpod/test_helpers.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxyfactory.rs
  src/state.rs
  src/xds/client.rs
Labels: size/XL

#826 dns: fix flaky test port reuse
  src/app.rs
  src/dns/server.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
Labels: size/M, release-notes-none

#831 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
