Repository istio/ztunnel, pull requests merged in 2025-05, with the labels that each got.

#1546 [release-1.24] Better support for root certificate
  build.rs
  src/admin.rs
  src/identity/caclient.rs
  src/test_helpers/ca.rs
  src/test_helpers/xds.rs
  src/tls/ca-key2.pem
  src/tls/certificate.rs
  src/tls/gen-certs.sh
  src/tls/lib.rs
  src/tls/mock.rs
  src/tls/root-cert2.pem
Labels: size/L

#1547 [release-1.25] Better support for root certificate
  build.rs
  src/admin.rs
  src/identity/caclient.rs
  src/test_helpers/ca.rs
  src/test_helpers/xds.rs
  src/tls/ca-key2.pem
  src/tls/certificate.rs
  src/tls/gen-certs.sh
  src/tls/lib.rs
  src/tls/mock.rs
  src/tls/root-cert2.pem
Labels: size/L

#1535 [release-1.26] fix istio_build metric
  src/version.rs
Labels: size/XS, release-notes-none

#1549 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1550 Make csr test stricter and more correct (previously #1432)
  Cargo.lock
  src/tls/csr.rs
Labels: size/L

#1552 backport-1.26 - Make csr test stricter and more correct (previously #1432) (#1550)
  Cargo.lock
  src/tls/csr.rs
Labels: size/L

#1545 show crypto provider in ztunnel version
  src/tls/lib.rs
  src/version.rs
Labels: size/S

#1553 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1554 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1557 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1558 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1507 Support TLS for metrics endpoint
  src/app.rs
  src/config.rs
  src/identity/manager.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/proxyfactory.rs
  src/test_helpers/app.rs
  src/test_helpers/linux.rs
  tests/namespaced.rs
Labels: ok-to-test, size/XL

#1559 remove git tag
  src/version.rs
Labels: size/XS

#1564 update how io errors are being generated to fix clippy issues
  src/identity/auth.rs
  src/proxy/h2.rs
  src/telemetry.rs
Labels: size/S
