Repository istio/ztunnel, pull requests merged in 2025-03, with the labels that each got.

#1474 Remove deadcode around BufReader
  src/copy.rs
Labels: size/M, release-notes-none

#1475 Drop service lookup that clones
  src/dns/server.rs
  src/state/service.rs
Labels: size/S, release-notes-none

#1477 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1420 Add inbound support for svc hostname in authority
  src/proxy.rs
  src/proxy/h2/server.rs
  src/proxy/inbound.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/state.rs
  src/test_helpers/namespaced.rs
  tests/namespaced.rs
Labels: size/XL

#1480 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1486 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1487 [1.25] deps: bump h2
  Cargo.lock
Labels: size/XS, release-notes-none

#1489 Automator: update common-files@release-1.25 in istio/ztunnel@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1490 misc refactors around inbound code
  src/baggage.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/state.rs
Labels: release-notes-none, size/XL

#1493 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1494 [release-1.25] Add xDS and CA headers/metadata support
  src/config.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/test_helpers/ca.rs
  src/xds/client.rs
Labels: size/L, release-notes-none

#1495 [release-1.25] Simplify the xDS/CA headers parse logic
  src/config.rs
Labels: size/S, release-notes-none

#1484 Move some code over to async closures
  src/drain.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/socks5.rs
  src/test_helpers/app.rs
  tests/direct.rs
Labels: size/L, release-notes-none

#1496 Include protocol in connection dump
  src/proxy/connection_manager.rs
  src/proxy/outbound.rs
  src/state/workload.rs
Labels: size/S, release-notes-none

#1498 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
