Repository istio/ztunnel, pull requests merged in 2025-06, with the labels that each got.

#1566 Allow dynamic configuration of thread count
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/app.rs
  src/config.rs
Labels: size/L, release-notes-none

#1461 Experimental Support for ambient on Windows
  .dockerignore
  Cargo.lock
  Cargo.toml
  Dockerfile.ztunnel-windows
  WINDOWS.md
  benches/basic.rs
  benches/throughput.rs
  build.rs
  common/scripts/report_build_info.ps1
  daemonset-windows.yaml
  examples/inpodserver.rs
  examples/windows-deploy.yaml
  examples/windows-hostprocess.yaml
  proto/zds.proto
  src/admin.rs
  src/app.rs
  src/config.rs
  src/dns/handler.rs
  src/dns/server.rs
  src/identity/caclient.rs
  src/inpod.rs
  src/inpod/linux.rs
  src/inpod/linux/admin.rs
  src/inpod/linux/config.rs
  src/inpod/linux/netns.rs
  src/inpod/linux/packet.rs
  src/inpod/linux/protocol.rs
  src/inpod/linux/statemanager.rs
  src/inpod/linux/test_helpers.rs
  src/inpod/linux/workloadmanager.rs
  src/inpod/windows.rs
  src/inpod/windows/admin.rs
  src/inpod/windows/config.rs
  src/inpod/windows/namespace.rs
  src/inpod/windows/packet.rs
  src/inpod/windows/protocol.rs
  src/inpod/windows/statemanager.rs
  src/inpod/windows/test_helpers.rs
  src/inpod/windows/workloadmanager.rs
  src/lib.rs
  src/proxy.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxyfactory.rs
  src/signal.rs
  src/socket.rs
  src/test_helpers.rs
  src/test_helpers/app.rs
  src/test_helpers/inpod_linux.rs
  src/test_helpers/linux.rs
  src/xds/client.rs
Labels: size/XXL, lifecycle/automatically-closed, windows

#1571 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1572 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1573 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1575 Automator: update common-files@release-1.25 in istio/ztunnel@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1578 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1579 Automator: update common-files@release-1.26 in istio/ztunnel@release-1.26
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1582 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
