Repository istio/ztunnel, pull requests merged in 2025-09, with the labels that each got.

#1626 Add open file metrics
  src/app.rs
  src/metrics.rs
  src/metrics/process.rs
  tests/direct.rs
Labels: size/L

#1635 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1567 retain valid certs on fetch failures
  src/identity/caclient.rs
  src/identity/manager.rs
Labels: size/L, ok-to-test

#1638 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1640 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none
