Repository istio/ztunnel, pull requests merged in 2025-01, with the labels that each got.

#1406 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1408 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1410 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1411 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#1409 xds: support overlapping IP addresses
  src/state/workload.rs
Labels: size/L, release-notes-none, cherrypick/release-1.24

#1412 [release-1.24] xds: support overlapping IP addresses
  src/state/workload.rs
Labels: size/L, release-notes-none

#1414 tests: improve error messages
  src/telemetry.rs
  src/test_helpers/namespaced.rs
  tests/namespaced.rs
Labels: size/L, release-notes-none

#1416 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1418 deps: drop http-types for specialized code
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  fuzz/fuzz_targets/baggage.rs
  src/proxy.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
Labels: size/L, release-notes-none

#1402 authorization: implement new serviceAccounts field
  benches/throughput.rs
  proto/authorization.proto
  src/admin.rs
  src/rbac.rs
Labels: size/M, release-notes-none

#1419 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1421 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1424 Bump prom_client to 0.23, fix a few build errors triggered by same
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/inpod/metrics.rs
  src/inpod/statemanager.rs
  src/inpod/workloadmanager.rs
  src/strng.rs
Labels: size/M

#1425 Reformat code with 1.84 rustc
  src/proxy/inbound.rs
  src/telemetry.rs
Labels: size/XS, release-notes-none, cherrypick/release-1.24

#1426 [release-1.24] Reformat code with 1.84 rustc
  src/proxy/inbound.rs
  src/telemetry.rs
Labels: size/XS, release-notes-none

#1427 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1428 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1430 Serialize SA match as camelCase
  src/rbac.rs
Labels: size/XS, release-notes-none

#1435 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1434 Resync proto with istio/istio
  proto/workload.proto
  src/admin.rs
  src/state/workload.rs
Labels: size/S, release-notes-none, cherrypick/release-1.25

#1440 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1441 metrics: add src/dst locality information to labels
  src/proxy/metrics.rs
  src/proxy/outbound.rs
Labels: size/M, release-notes-none

#1443 Add new ztunnel images
  images/ztunnel-blue-on-dark.png
  images/ztunnel-blue-on-dark.svg
  images/ztunnel-blue-on-light.png
  images/ztunnel-blue-on-light.svg
  images/ztunnel-blue-on-transparent.png
  images/ztunnel-blue-on-transparent.svg
  images/ztunnel-dark-on-light.png
  images/ztunnel-dark-on-light.svg
  images/ztunnel-dark-on-transparent.png
  images/ztunnel-dark-on-transparent.svg
  images/ztunnel-gray-on-light.png
  images/ztunnel-gray-on-light.svg
  images/ztunnel-gray-on-transparent.png
  images/ztunnel-gray-on-transparent.svg
  images/ztunnel-light-on-blue.png
  images/ztunnel-light-on-blue.svg
Labels: size/S

#1442 [release-1.25] metrics: add src/dst locality information to labels
  src/proxy/metrics.rs
  src/proxy/outbound.rs
Labels: size/M, release-notes-none
