Repository istio/ztunnel, pull requests merged in 2025-08, with the labels that each got.

#1607 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1614 Update rust version and dependencies
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/admin.rs
  src/hyper_util.rs
  src/inpod/netns.rs
  src/proxy/inbound.rs
  src/socket.rs
  src/test_helpers/linux.rs
  src/tls/certificate.rs
Labels: size/XXL

#1616 Automator: update common-files@release-1.25 in istio/ztunnel@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1618 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1619 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1621 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1620 Update ztunnel profiling doc
  PROFILING.md
Labels: size/S

#1622 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none
