Repository istio/ztunnel, pull requests merged in 2025-07, with the labels that each got.

#1565 Multinetwork/Support remote networks for services with waypoints
  src/proxy.rs
  src/proxy/outbound.rs
Labels: size/L, ok-to-test

#1587 [release-1.27] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#1588 Automator: update common-files@release-1.27 in istio/ztunnel@release-1.27
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1589 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1593 Automator: update common-files@release-1.26 in istio/ztunnel@release-1.26
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1591 [release-1.27] Buffer inner h2 streams
  src/proxy/h2.rs
  src/proxy/pool.rs
Labels: size/M, release-notes-none

#1592 [release-1.27] Multinetwork/Support remote networks for services with waypoints
  src/proxy.rs
  src/proxy/outbound.rs
Labels: size/L, release-notes-none

#1595 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1596 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1597 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1598 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1599 adopt rcgen 14
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/tls/certificate.rs
  src/tls/mock.rs
Labels: size/M

#1601 respect IPV6 setting for DNS server
  src/config.rs
  src/dns/server.rs
  src/proxyfactory.rs
  src/test_helpers/dns.rs
Labels: size/M
