Repository istio/ztunnel, pull requests merged in 2025-04, with the labels that each got.

#1499 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1501 PROXY Protocol: send to localhost
  src/config.rs
  src/proxy/inbound.rs
  src/state/workload.rs
  src/test_helpers/linux.rs
Labels: size/M

#1502 send PROXY to localhost by default
  src/config.rs
Labels: size/XS

#1503 Fix docs on building with boringssl
  README.md
Labels: size/XS

#1504 Use fewer unwraps and use generic `NamespacedHostname::from_str`
  src/state.rs
  src/xds.rs
Labels: size/M

#1505 Regenerate certs with a valid CA
  src/admin.rs
  src/tls/ca-key.pem
  src/tls/cert-chain.pem
  src/tls/cert.pem
  src/tls/gen-certs.sh
  src/tls/intermediary-cert.pem
  src/tls/intermediary-key.pem
  src/tls/istiod-cert.pem
  src/tls/istiod-key.pem
  src/tls/root-cert.pem
Labels: size/L, release-notes-none

#1506 Fix markdown link formatting for aws-lc
  README.md
Labels: size/XS, ok-to-test

#1429 WIP: Feature/double hbone
  benches/throughput.rs
  src/cert_fetcher.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/h2.rs
  src/proxy/h2/client.rs
  src/proxy/inbound.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
  src/test_helpers/linux.rs
  src/test_helpers/tcp.rs
  src/tls/workload.rs
  tests/namespaced.rs
Labels: size/XXL

#1512 improve dns accesslog
  src/dns/server.rs
Labels: size/M

#1513 chore: fix make failed on mac
  Makefile.overrides.mk
Labels: size/XS

#1514 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1515 Automator: update common-files@release-1.23 in istio/ztunnel@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1516 Automator: update common-files@release-1.24 in istio/ztunnel@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1517 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
Labels: auto-merge, release-notes-none, size/XL

#1519 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1523 Automator: update common-files@release-1.25 in istio/ztunnel@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1510 Better support for root certificates
  build.rs
  src/admin.rs
  src/identity/caclient.rs
  src/test_helpers/ca.rs
  src/test_helpers/xds.rs
  src/tls/ca-key2.pem
  src/tls/certificate.rs
  src/tls/gen-certs.sh
  src/tls/lib.rs
  src/tls/mock.rs
  src/tls/root-cert2.pem
Labels: size/L, release-notes-none, cherrypick/release-1.24, cherrypick/release-1.25

#1529 Include error info in DNS access logs
  src/dns/server.rs
Labels: size/S, release-notes-none

#1528 [release-1.26] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#1533 Automator: update common-files@release-1.26 in istio/ztunnel@release-1.26
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1532 fix istio_build metric
  src/version.rs
Labels: size/XS, cherrypick/release-1.25, cherrypick/release-1.26

#1534 [release-1.25] fix istio_build metric
  src/version.rs
Labels: size/XS, release-notes-none

#1539 http2: tune connection window size and add config
  src/config.rs
Labels: size/S, release-notes-none, cherrypick/release-1.24, cherrypick/release-1.25, cherrypick/release-1.26

#1541 [release-1.25] http2: tune connection window size and add config
  src/config.rs
Labels: size/S, release-notes-none

#1542 [release-1.26] http2: tune connection window size and add config
  src/config.rs
Labels: size/S, release-notes-none

#1540 [release-1.24] http2: tune connection window size and add config
  src/config.rs
Labels: size/S, release-notes-none

#1543 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1544 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
