Repository istio/ztunnel, pull requests merged in 2025-02, with the labels that each got.

#1445 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1451 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1449 bump dependencies
  Cargo.lock
  fuzz/Cargo.lock
  src/admin.rs
  src/dns/metrics.rs
Labels: size/XXL, release-notes-none

#1454 Automator: update common-files@release-1.25 in istio/ztunnel@release-1.25
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1455 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1458 Bump dependencies
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  src/admin.rs
  src/copy.rs
  src/dns/server.rs
  src/proxy.rs
  src/state.rs
  src/tls/mock.rs
Labels: size/L, release-notes-none

#1459 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1452 Add xDS and CA headers/metadata support
  src/config.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/test_helpers/ca.rs
  src/xds/client.rs
Labels: size/L

#1460 Simplify the xDS/CA headers parse logic
  src/config.rs
Labels: size/S

#1463 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1465 Update to Rust edition 2024
  Cargo.lock
  Cargo.toml
  benches/basic.rs
  benches/throughput.rs
  examples/inpodserver.rs
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  fuzz/fuzz_targets/baggage.rs
  src/admin.rs
  src/app.rs
  src/baggage.rs
  src/config.rs
  src/copy.rs
  src/dns/server.rs
  src/hyper_util.rs
  src/identity.rs
  src/identity/caclient.rs
  src/identity/manager.rs
  src/inpod/netns.rs
  src/inpod/packet.rs
  src/inpod/protocol.rs
  src/inpod/statemanager.rs
  src/inpod/test_helpers.rs
  src/inpod/workloadmanager.rs
  src/main.rs
  src/metrics.rs
  src/proxy.rs
  src/proxy/connection_manager.rs
  src/proxy/h2.rs
  src/proxy/h2/client.rs
  src/proxy/h2/server.rs
  src/proxy/inbound.rs
  src/proxy/inbound_passthrough.rs
  src/proxy/metrics.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
  src/proxy/socks5.rs
  src/rbac.rs
  src/signal.rs
  src/state.rs
  src/state/service.rs
  src/state/workload.rs
  src/telemetry.rs
  src/test_helpers.rs
  src/test_helpers/dns.rs
  src/test_helpers/hyper_tower.rs
  src/test_helpers/linux.rs
  src/test_helpers/namespaced.rs
  src/test_helpers/netns.rs
  src/test_helpers/tcp.rs
  src/tls/certificate.rs
  src/tls/control.rs
  src/tls/mock.rs
  src/tls/workload.rs
  src/version.rs
  src/xds.rs
  src/xds/client.rs
  tests/namespaced.rs
Labels: release-notes-none, size/XL

#1466 Add support for AWS-LC-RS TLS provider
  Cargo.lock
  Cargo.toml
  Makefile.core.mk
  README.md
  deny.toml
  scripts/release.sh
  src/tls.rs
  src/tls/csr.rs
  src/tls/lib.rs
Labels: size/L

#1468 Automator: update common-files@master in istio/ztunnel@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1469 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1471 Automator: update common-files@master in istio/ztunnel@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1470 Add benchmarks for load balancing
  benches/basic.rs
Labels: size/L, release-notes-none

#1436 Add support for OpenSSL
  Cargo.lock
  Cargo.toml
  Makefile.core.mk
  README.md
  deny.toml
  scripts/release.sh
  src/tls.rs
  src/tls/csr.rs
  src/tls/lib.rs
Labels: size/L, ok-to-test

#1472 Implement capacity
  proto/workload.proto
  src/admin.rs
  src/proxy.rs
  src/state.rs
  src/state/workload.rs
  src/test_helpers.rs
Labels: size/M, release-notes-none

#1467 tls: move to `tls-aws-lc` by default
  Cargo.toml
  README.md
  fuzz/Cargo.lock
Labels: size/L

#1453 Remove ConnClient, it's pointless now
  src/proxy/h2/client.rs
  src/proxy/outbound.rs
  src/proxy/pool.rs
Labels: size/L
